/**
 * Unified Commit Generator
 *
 * Generates commit messages and PR comments for all Git providers.
 * Supports GitHub, GitLab, Bitbucket, and Azure DevOps.
 *
 * Key features:
 * - Consistent commit message format across providers
 * - Respects provider-specific limits (title length, body format)
 * - Groups issues by category, severity, or file
 * - Generates educational content and references
 */

import {
  Provider,
  CommitStyle,
  CommitGroup,
  FixReportIssue,
  IssueCategory,
  IssueSeverity,
  FixCommit,
  CommitTemplate,
} from '../types/fix-report-types';

// ============================================================================
// Provider-Specific Templates
// ============================================================================

export const PROVIDER_TEMPLATES: Record<Provider, CommitTemplate> = {
  github: {
    provider: 'github',
    titleTemplate: '{type}({scope}): {description}',
    bodyTemplate: `## Summary
{summary}

## Issues Fixed
{issues}

## Files Changed
{files}

{educational}`,
    footerTemplate: `---
Generated by [CodeQual](https://codequal.dev)
Co-Authored-By: CodeQual Bot <bot@codequal.dev>`,
    maxTitleLength: 72,
    maxBodyLength: 65535,
  },
  gitlab: {
    provider: 'gitlab',
    titleTemplate: '{type}({scope}): {description}',
    bodyTemplate: `### Summary
{summary}

### Issues Fixed
{issues}

### Files Changed
{files}

{educational}`,
    footerTemplate: `---
Generated by [CodeQual](https://codequal.dev)`,
    maxTitleLength: 100,
    maxBodyLength: 1000000,
  },
  bitbucket: {
    provider: 'bitbucket',
    titleTemplate: '{type}: {description}',
    bodyTemplate: `**Summary**
{summary}

**Issues Fixed**
{issues}

**Files Changed**
{files}`,
    footerTemplate: `

---
Generated by CodeQual`,
    maxTitleLength: 255,
    maxBodyLength: 65535,
  },
  azure_devops: {
    provider: 'azure_devops',
    titleTemplate: '{type}({scope}): {description}',
    bodyTemplate: `## Summary
{summary}

## Issues Fixed
{issues}

## Files Changed
{files}

{educational}`,
    footerTemplate: `

---
Generated by [CodeQual](https://codequal.dev)`,
    maxTitleLength: 400,
    maxBodyLength: 100000,
  },
};

// ============================================================================
// Commit Type Mapping
// ============================================================================

const CATEGORY_TO_COMMIT_TYPE: Record<IssueCategory, string> = {
  security: 'fix(security)',
  code_quality: 'fix',
  performance: 'perf',
  architecture: 'refactor',
  dependency_vulnerability: 'fix(deps)',
  code_style: 'style',
  best_practice: 'fix',
  documentation: 'docs',
};

const SEVERITY_EMOJI: Record<IssueSeverity, string> = {
  critical: '🚨',
  high: '🔴',
  medium: '🟠',
  low: '🟡',
  info: '💡',
};

// ============================================================================
// Commit Generator Class
// ============================================================================

export class UnifiedCommitGenerator {
  private provider: Provider;
  private template: CommitTemplate;

  constructor(provider: Provider = 'github') {
    this.provider = provider;
    this.template = PROVIDER_TEMPLATES[provider];
  }

  /**
   * Generate commits based on user selection style
   */
  generateCommits(
    issues: FixReportIssue[],
    commitStyle: CommitStyle,
    repositoryName?: string
  ): FixCommit[] {
    const selectedIssues = issues.filter((i) => i.userSelected && i.fixAvailable);

    if (selectedIssues.length === 0) {
      return [];
    }

    switch (commitStyle) {
      case 'single':
        return [this.generateSingleCommit(selectedIssues, repositoryName)];

      case 'grouped':
        return this.generateGroupedCommits(selectedIssues, repositoryName);

      case 'per_file':
        return this.generatePerFileCommits(selectedIssues, repositoryName);

      case 'per_issue':
        return this.generatePerIssueCommits(selectedIssues, repositoryName);

      default:
        return [this.generateSingleCommit(selectedIssues, repositoryName)];
    }
  }

  /**
   * Generate a single commit for all issues
   */
  private generateSingleCommit(
    issues: FixReportIssue[],
    repositoryName?: string
  ): FixCommit {
    const primaryCategory = this.getPrimaryCategory(issues);
    const commitType = CATEGORY_TO_COMMIT_TYPE[primaryCategory];
    const scope = repositoryName || 'all';

    const title = this.formatTitle(commitType, scope, `fix ${issues.length} issues`);
    const body = this.formatBody(issues);

    return {
      id: this.generateId(),
      fixReportId: '',
      commitType: this.mapToCommitType(primaryCategory),
      commitTitle: title,
      commitBody: body,
      filesChanged: this.getUniqueFiles(issues),
      additions: 0,
      deletions: 0,
      issueIds: issues.map((i) => i.id),
      status: 'pending',
      createdAt: new Date(),
    };
  }

  /**
   * Generate commits grouped by category
   */
  private generateGroupedCommits(
    issues: FixReportIssue[],
    repositoryName?: string
  ): FixCommit[] {
    const groups = this.groupByCategory(issues);

    return groups.map((group) => {
      const commitType = CATEGORY_TO_COMMIT_TYPE[group.category!];
      const scope = repositoryName || group.category;

      const title = this.formatTitle(
        commitType,
        scope!,
        `fix ${group.issues.length} ${group.category} issues`
      );
      const body = this.formatBody(group.issues);

      return {
        id: this.generateId(),
        fixReportId: '',
        commitType: this.mapToCommitType(group.category!),
        commitTitle: title,
        commitBody: body,
        filesChanged: this.getUniqueFiles(group.issues),
        additions: 0,
        deletions: 0,
        issueIds: group.issues.map((i) => i.id),
        status: 'pending',
        createdAt: new Date(),
      };
    });
  }

  /**
   * Generate commits per file
   */
  private generatePerFileCommits(
    issues: FixReportIssue[],
    repositoryName?: string
  ): FixCommit[] {
    const groups = this.groupByFile(issues);

    return groups.map((group) => {
      const primaryCategory = this.getPrimaryCategory(group.issues);
      const commitType = CATEGORY_TO_COMMIT_TYPE[primaryCategory];
      const fileName = group.file!.split('/').pop() || group.file;

      const title = this.formatTitle(
        commitType,
        fileName!,
        `fix ${group.issues.length} issues`
      );
      const body = this.formatBody(group.issues);

      return {
        id: this.generateId(),
        fixReportId: '',
        commitType: this.mapToCommitType(primaryCategory),
        commitTitle: title,
        commitBody: body,
        filesChanged: [group.file!],
        additions: 0,
        deletions: 0,
        issueIds: group.issues.map((i) => i.id),
        status: 'pending',
        createdAt: new Date(),
      };
    });
  }

  /**
   * Generate one commit per issue
   */
  private generatePerIssueCommits(
    issues: FixReportIssue[],
    _repositoryName?: string
  ): FixCommit[] {
    return issues.map((issue) => {
      const commitType = CATEGORY_TO_COMMIT_TYPE[issue.category];
      const fileName = issue.filePath.split('/').pop() || issue.filePath;

      const title = this.formatTitle(commitType, fileName, this.truncate(issue.message, 50));
      const body = this.formatSingleIssueBody(issue);

      return {
        id: this.generateId(),
        fixReportId: '',
        commitType: this.mapToCommitType(issue.category),
        commitTitle: title,
        commitBody: body,
        filesChanged: [issue.filePath],
        additions: 0,
        deletions: 0,
        issueIds: [issue.id],
        status: 'pending',
        createdAt: new Date(),
      };
    });
  }

  // ============================================================================
  // Formatting Helpers
  // ============================================================================

  private formatTitle(type: string, scope: string, description: string): string {
    let title = this.template.titleTemplate
      .replace('{type}', type)
      .replace('{scope}', scope)
      .replace('{description}', description);

    // Truncate if needed
    if (title.length > this.template.maxTitleLength) {
      title = title.substring(0, this.template.maxTitleLength - 3) + '...';
    }

    return title;
  }

  private formatBody(issues: FixReportIssue[]): string {
    const summary = this.generateSummary(issues);
    const issuesList = this.formatIssuesList(issues);
    const filesList = this.formatFilesList(issues);
    const educational = this.generateEducationalContent(issues);

    let body = this.template.bodyTemplate
      .replace('{summary}', summary)
      .replace('{issues}', issuesList)
      .replace('{files}', filesList)
      .replace('{educational}', educational);

    body += '\n' + this.template.footerTemplate;

    // Truncate if needed
    if (body.length > this.template.maxBodyLength) {
      body = body.substring(0, this.template.maxBodyLength - 100) + '\n\n[Truncated...]';
    }

    return body;
  }

  private formatSingleIssueBody(issue: FixReportIssue): string {
    const summary = `Fixed ${issue.category} issue: ${issue.message}`;
    const issuesList = this.formatSingleIssue(issue);
    const filesList = `- \`${issue.filePath}\``;
    const educational = this.generateEducationalForRule(issue.ruleId, issue.tool);

    let body = this.template.bodyTemplate
      .replace('{summary}', summary)
      .replace('{issues}', issuesList)
      .replace('{files}', filesList)
      .replace('{educational}', educational);

    body += '\n' + this.template.footerTemplate;

    return body;
  }

  private generateSummary(issues: FixReportIssue[]): string {
    const bySeverity = this.countBySeverity(issues);
    const byCategory = this.countByCategory(issues);

    const severityParts: string[] = [];
    for (const [severity, count] of Object.entries(bySeverity)) {
      if (count > 0) {
        severityParts.push(`${count} ${severity}`);
      }
    }

    const categoryParts: string[] = [];
    for (const [category, count] of Object.entries(byCategory)) {
      if (count > 0) {
        categoryParts.push(`${count} ${category.replace('_', ' ')}`);
      }
    }

    return `This commit fixes ${issues.length} issues:\n- By severity: ${severityParts.join(', ')}\n- By category: ${categoryParts.join(', ')}`;
  }

  private formatIssuesList(issues: FixReportIssue[]): string {
    // Group by severity for display
    const grouped: Record<string, FixReportIssue[]> = {};
    for (const issue of issues) {
      if (!grouped[issue.severity]) {
        grouped[issue.severity] = [];
      }
      grouped[issue.severity].push(issue);
    }

    const lines: string[] = [];
    const severityOrder: IssueSeverity[] = ['critical', 'high', 'medium', 'low', 'info'];

    for (const severity of severityOrder) {
      const severityIssues = grouped[severity];
      if (severityIssues && severityIssues.length > 0) {
        lines.push(`\n### ${SEVERITY_EMOJI[severity]} ${severity.toUpperCase()} (${severityIssues.length})`);

        for (const issue of severityIssues.slice(0, 10)) {
          lines.push(this.formatSingleIssue(issue));
        }

        if (severityIssues.length > 10) {
          lines.push(`  _... and ${severityIssues.length - 10} more ${severity} issues_`);
        }
      }
    }

    return lines.join('\n');
  }

  private formatSingleIssue(issue: FixReportIssue): string {
    const location = `${issue.filePath}:${issue.lineNumber}`;
    const source = issue.fixSource === 'pattern' ? '(pattern)' : '(AI)';
    return `- **${issue.ruleId}** at \`${location}\` ${source}\n  ${this.truncate(issue.message, 100)}`;
  }

  private formatFilesList(issues: FixReportIssue[]): string {
    const files = this.getUniqueFiles(issues);
    const fileLines = files.slice(0, 20).map((f) => `- \`${f}\``);

    if (files.length > 20) {
      fileLines.push(`_... and ${files.length - 20} more files_`);
    }

    return fileLines.join('\n');
  }

  private generateEducationalContent(issues: FixReportIssue[]): string {
    // Get unique rules
    const rules = new Set(issues.map((i) => `${i.tool}:${i.ruleId}`));

    if (rules.size === 0) {
      return '';
    }

    const lines = ['## Learn More'];

    // Add links for top rules
    const rulesList = Array.from(rules).slice(0, 5);
    for (const rule of rulesList) {
      const [tool, ruleId] = rule.split(':');
      const link = this.getRuleDocLink(tool, ruleId);
      if (link) {
        lines.push(`- [${ruleId}](${link})`);
      }
    }

    return lines.length > 1 ? lines.join('\n') : '';
  }

  private generateEducationalForRule(ruleId: string, tool: string): string {
    const link = this.getRuleDocLink(tool, ruleId);
    if (link) {
      return `## Learn More\n- [${ruleId} documentation](${link})`;
    }
    return '';
  }

  private getRuleDocLink(tool: string, ruleId: string): string | null {
    switch (tool.toLowerCase()) {
      case 'semgrep':
        return `https://semgrep.dev/r/${ruleId}`;
      case 'eslint':
        return `https://eslint.org/docs/rules/${ruleId}`;
      case 'pmd':
        return `https://pmd.github.io/pmd/rules/java/`;
      case 'checkstyle':
        return `https://checkstyle.org/checks/`;
      default:
        return null;
    }
  }

  // ============================================================================
  // Grouping Helpers
  // ============================================================================

  private groupByCategory(issues: FixReportIssue[]): CommitGroup[] {
    const groups: Record<string, FixReportIssue[]> = {};

    for (const issue of issues) {
      if (!groups[issue.category]) {
        groups[issue.category] = [];
      }
      groups[issue.category].push(issue);
    }

    return Object.entries(groups).map(([category, categoryIssues]) => ({
      category: category as IssueCategory,
      issues: categoryIssues,
      title: '',
      body: '',
    }));
  }

  private groupByFile(issues: FixReportIssue[]): CommitGroup[] {
    const groups: Record<string, FixReportIssue[]> = {};

    for (const issue of issues) {
      if (!groups[issue.filePath]) {
        groups[issue.filePath] = [];
      }
      groups[issue.filePath].push(issue);
    }

    return Object.entries(groups).map(([file, fileIssues]) => ({
      file,
      issues: fileIssues,
      title: '',
      body: '',
    }));
  }

  // ============================================================================
  // Utility Helpers
  // ============================================================================

  private getPrimaryCategory(issues: FixReportIssue[]): IssueCategory {
    const counts = this.countByCategory(issues);
    let maxCategory: IssueCategory = 'code_quality';
    let maxCount = 0;

    for (const [category, count] of Object.entries(counts)) {
      if (count > maxCount) {
        maxCount = count;
        maxCategory = category as IssueCategory;
      }
    }

    return maxCategory;
  }

  private countBySeverity(issues: FixReportIssue[]): Record<IssueSeverity, number> {
    const counts: Record<IssueSeverity, number> = {
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      info: 0,
    };

    for (const issue of issues) {
      counts[issue.severity]++;
    }

    return counts;
  }

  private countByCategory(issues: FixReportIssue[]): Record<IssueCategory, number> {
    const counts: Record<IssueCategory, number> = {
      security: 0,
      code_quality: 0,
      performance: 0,
      architecture: 0,
      dependency_vulnerability: 0,
      code_style: 0,
      best_practice: 0,
      documentation: 0,
    };

    for (const issue of issues) {
      counts[issue.category]++;
    }

    return counts;
  }

  private getUniqueFiles(issues: FixReportIssue[]): string[] {
    return Array.from(new Set(issues.map((i) => i.filePath)));
  }

  private mapToCommitType(
    category: IssueCategory
  ): 'fix' | 'style' | 'security' | 'perf' | 'refactor' {
    switch (category) {
      case 'security':
      case 'dependency_vulnerability':
        return 'security';
      case 'performance':
        return 'perf';
      case 'code_style':
        return 'style';
      case 'architecture':
        return 'refactor';
      default:
        return 'fix';
    }
  }

  private truncate(str: string, maxLength: number): string {
    if (str.length <= maxLength) {
      return str;
    }
    return str.substring(0, maxLength - 3) + '...';
  }

  private generateId(): string {
    return 'commit-' + Math.random().toString(36).substring(2, 15);
  }

  // ============================================================================
  // PR Comment Generation
  // ============================================================================

  /**
   * Generate a PR comment summarizing the fixes
   */
  generatePRComment(
    issues: FixReportIssue[],
    commits: FixCommit[],
    repositoryUrl: string,
    prNumber: number
  ): string {
    const selectedIssues = issues.filter((i) => i.userSelected && i.fixAvailable);
    const intentionalIssues = issues.filter((i) => i.isIntentionalUse);
    const manualReviewIssues = issues.filter(
      (i) => !i.fixAvailable && !i.isIntentionalUse
    );

    const lines: string[] = [
      `## 🔧 CodeQual Auto-Fix Report`,
      '',
      `### Summary`,
      `- **Total issues found:** ${issues.length}`,
      `- **Auto-fixed:** ${selectedIssues.length}`,
      `- **Commits created:** ${commits.length}`,
      '',
    ];

    // Severity breakdown
    const bySeverity = this.countBySeverity(selectedIssues);
    lines.push('### Issues Fixed by Severity');
    lines.push('| Severity | Count |');
    lines.push('|----------|-------|');
    for (const [severity, count] of Object.entries(bySeverity)) {
      if (count > 0) {
        lines.push(`| ${SEVERITY_EMOJI[severity as IssueSeverity]} ${severity} | ${count} |`);
      }
    }
    lines.push('');

    // Intentional use section
    if (intentionalIssues.length > 0) {
      lines.push('### 🔍 Security Review Required');
      lines.push(
        `The following ${intentionalIssues.length} items appear to be **intentional use** of security-sensitive APIs:`
      );
      for (const issue of intentionalIssues.slice(0, 5)) {
        lines.push(`- \`${issue.filePath}:${issue.lineNumber}\` - ${issue.intentionalReason}`);
      }
      if (intentionalIssues.length > 5) {
        lines.push(`- _... and ${intentionalIssues.length - 5} more_`);
      }
      lines.push('');
      lines.push('> These are not security vulnerabilities but should be reviewed to ensure proper handling.');
      lines.push('');
    }

    // Manual review section
    if (manualReviewIssues.length > 0) {
      lines.push('### 📋 Manual Review Required');
      lines.push(
        `${manualReviewIssues.length} issues could not be auto-fixed and require manual attention.`
      );
      lines.push('');
    }

    // Commits section
    lines.push('### Commits');
    for (const commit of commits) {
      lines.push(`- \`${commit.commitTitle}\``);
    }
    lines.push('');

    // Footer
    lines.push('---');
    lines.push('*Generated by [CodeQual](https://codequal.dev)*');

    return lines.join('\n');
  }
}

// ============================================================================
// Export Singleton Factory
// ============================================================================

export function createCommitGenerator(provider: Provider = 'github'): UnifiedCommitGenerator {
  return new UnifiedCommitGenerator(provider);
}
