#!/bin/bash
echo "Checking formatter fixes in agent implementations"
echo "-------------------------------------------"
echo "Comparing claude-agent.ts message formatting"
grep -A 5 "// Remove the severity tag and any leading dash or whitespace" "/Users/alpinro/Code Prjects/codequal/packages/agents/src/claude/claude-agent.ts"
echo ""
echo "Comparing claude-agent.ts suggestion formatting"
grep -A 5 "// Remove any leading dash, comma, or whitespace" "/Users/alpinro/Code Prjects/codequal/packages/agents/src/claude/claude-agent.ts"
echo ""
echo "Comparing gemini-agent.ts message formatting"
grep -A 5 "// Remove the severity tag and any leading dash or whitespace" "/Users/alpinro/Code Prjects/codequal/packages/agents/src/gemini/gemini-agent.ts"
echo ""
echo "Comparing gemini-agent.ts suggestion formatting"
grep -A 5 "// Remove any leading dash, comma, or whitespace" "/Users/alpinro/Code Prjects/codequal/packages/agents/src/gemini/gemini-agent.ts"
echo ""
echo "Comparing deepseek-agent.ts message formatting"
grep -A 5 "// Remove the severity tag and any leading dash or whitespace" "/Users/alpinro/Code Prjects/codequal/packages/agents/src/deepseek/deepseek-agent.ts"
echo ""
echo "Comparing deepseek-agent.ts suggestion formatting"
grep -A 5 "// Remove any leading dash, comma, or whitespace" "/Users/alpinro/Code Prjects/codequal/packages/agents/src/deepseek/deepseek-agent.ts"
