"use strict";
/**
 * Comprehensive ESLint Core Rules
 *
 * Contains ALL ESLint core rules organized by category.
 * Data sourced from: https://eslint.org/docs/latest/rules/
 *
 * Categories:
 * - Possible Problems: Rules that catch runtime errors
 * - Suggestions: Best practices and code quality
 * - Layout & Formatting: Code style (mostly deprecated in favor of @stylistic)
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ALL_ESLINT_RULES = exports.ESLINT_DEPRECATED = exports.ESLINT_LAYOUT = exports.ESLINT_SUGGESTIONS = exports.ESLINT_POSSIBLE_PROBLEMS = void 0;
exports.getESLintRuleStats = getESLintRuleStats;
// =============================================================================
// POSSIBLE PROBLEMS - Rules that detect potential runtime errors
// =============================================================================
exports.ESLINT_POSSIBLE_PROBLEMS = {
    'array-callback-return': { type: 'quality', fixable: false, description: 'Enforce return in array callbacks' },
    'constructor-super': { type: 'quality', fixable: false, description: 'Require super() in constructors' },
    'for-direction': { type: 'quality', fixable: false, description: 'Enforce for loop counter direction' },
    'getter-return': { type: 'quality', fixable: false, description: 'Enforce return in getters' },
    'no-async-promise-executor': { type: 'quality', fixable: false, description: 'Disallow async Promise executors' },
    'no-await-in-loop': { type: 'performance', fixable: false, description: 'Disallow await in loops' },
    'no-class-assign': { type: 'quality', fixable: false, description: 'Disallow reassigning class' },
    'no-compare-neg-zero': { type: 'quality', fixable: false, description: 'Disallow comparing to -0' },
    'no-cond-assign': { type: 'quality', fixable: false, description: 'Disallow assignment in conditions' },
    'no-const-assign': { type: 'quality', fixable: false, description: 'Disallow reassigning const' },
    'no-constant-binary-expression': { type: 'quality', fixable: false, description: 'Disallow constant binary expressions' },
    'no-constant-condition': { type: 'quality', fixable: false, description: 'Disallow constant conditions' },
    'no-constructor-return': { type: 'quality', fixable: false, description: 'Disallow return in constructor' },
    'no-control-regex': { type: 'quality', fixable: false, description: 'Disallow control characters in regex' },
    'no-debugger': { type: 'quality', fixable: true, description: 'Disallow debugger' },
    'no-dupe-args': { type: 'quality', fixable: false, description: 'Disallow duplicate arguments' },
    'no-dupe-class-members': { type: 'quality', fixable: false, description: 'Disallow duplicate class members' },
    'no-dupe-else-if': { type: 'quality', fixable: false, description: 'Disallow duplicate else-if conditions' },
    'no-dupe-keys': { type: 'quality', fixable: false, description: 'Disallow duplicate keys' },
    'no-duplicate-case': { type: 'quality', fixable: false, description: 'Disallow duplicate case labels' },
    'no-duplicate-imports': { type: 'quality', fixable: false, description: 'Disallow duplicate imports' },
    'no-empty-character-class': { type: 'quality', fixable: false, description: 'Disallow empty character classes' },
    'no-empty-pattern': { type: 'quality', fixable: false, description: 'Disallow empty destructuring patterns' },
    'no-ex-assign': { type: 'quality', fixable: false, description: 'Disallow reassigning exceptions' },
    'no-fallthrough': { type: 'quality', fixable: false, description: 'Disallow case fallthrough' },
    'no-func-assign': { type: 'quality', fixable: false, description: 'Disallow reassigning functions' },
    'no-import-assign': { type: 'quality', fixable: false, description: 'Disallow assigning to imports' },
    'no-inner-declarations': { type: 'quality', fixable: false, description: 'Disallow nested function/var declarations' },
    'no-invalid-regexp': { type: 'quality', fixable: false, description: 'Disallow invalid regex' },
    'no-irregular-whitespace': { type: 'style', fixable: false, description: 'Disallow irregular whitespace' },
    'no-loss-of-precision': { type: 'quality', fixable: false, description: 'Disallow number precision loss' },
    'no-misleading-character-class': { type: 'quality', fixable: true, description: 'Disallow misleading char classes' },
    'no-new-native-nonconstructor': { type: 'quality', fixable: false, description: 'Disallow new on non-constructors' },
    'no-obj-calls': { type: 'quality', fixable: false, description: 'Disallow calling globals as functions' },
    'no-promise-executor-return': { type: 'quality', fixable: false, description: 'Disallow return in Promise executor' },
    'no-prototype-builtins': { type: 'security', fixable: false, description: 'Disallow Object.prototype methods' },
    'no-self-assign': { type: 'quality', fixable: false, description: 'Disallow self-assignment' },
    'no-self-compare': { type: 'quality', fixable: false, description: 'Disallow self-comparison' },
    'no-setter-return': { type: 'quality', fixable: false, description: 'Disallow return in setters' },
    'no-sparse-arrays': { type: 'quality', fixable: false, description: 'Disallow sparse arrays' },
    'no-template-curly-in-string': { type: 'quality', fixable: false, description: 'Disallow template literal confusion' },
    'no-this-before-super': { type: 'quality', fixable: false, description: 'Disallow this/super before super()' },
    'no-undef': { type: 'quality', fixable: false, description: 'Disallow undeclared variables' },
    'no-unexpected-multiline': { type: 'quality', fixable: false, description: 'Disallow confusing multiline' },
    'no-unmodified-loop-condition': { type: 'quality', fixable: false, description: 'Disallow unmodified loop conditions' },
    'no-unreachable': { type: 'quality', fixable: false, description: 'Disallow unreachable code' },
    'no-unreachable-loop': { type: 'quality', fixable: false, description: 'Disallow unreachable loops' },
    'no-unsafe-finally': { type: 'quality', fixable: false, description: 'Disallow control flow in finally' },
    'no-unsafe-negation': { type: 'quality', fixable: true, description: 'Disallow negation on left side' },
    'no-unsafe-optional-chaining': { type: 'quality', fixable: false, description: 'Disallow unsafe optional chaining' },
    'no-unused-private-class-members': { type: 'quality', fixable: false, description: 'Disallow unused private members' },
    'no-unused-vars': { type: 'quality', fixable: false, description: 'Disallow unused variables' },
    'no-use-before-define': { type: 'quality', fixable: false, description: 'Disallow use before define' },
    'no-useless-assignment': { type: 'quality', fixable: false, description: 'Disallow useless assignments' },
    'no-useless-backreference': { type: 'quality', fixable: false, description: 'Disallow useless backreferences' },
    'require-atomic-updates': { type: 'quality', fixable: false, description: 'Disallow race condition assignments' },
    'use-isnan': { type: 'quality', fixable: false, description: 'Require isNaN() for NaN checks' },
    'valid-typeof': { type: 'quality', fixable: true, description: 'Enforce valid typeof comparisons' },
};
// =============================================================================
// SUGGESTIONS - Best practices and code quality improvements
// =============================================================================
exports.ESLINT_SUGGESTIONS = {
    'accessor-pairs': { type: 'quality', fixable: false, description: 'Enforce getter/setter pairs' },
    'arrow-body-style': { type: 'style', fixable: true, description: 'Arrow function brace style' },
    'block-scoped-var': { type: 'quality', fixable: false, description: 'Enforce block scope for var' },
    'camelcase': { type: 'style', fixable: false, description: 'Enforce camelCase naming' },
    'capitalized-comments': { type: 'style', fixable: true, description: 'Enforce capitalized comments' },
    'class-methods-use-this': { type: 'quality', fixable: false, description: 'Require this in class methods' },
    'complexity': { type: 'maintainability', fixable: false, description: 'Enforce complexity limit' },
    'consistent-return': { type: 'quality', fixable: false, description: 'Consistent return statements' },
    'consistent-this': { type: 'style', fixable: false, description: 'Consistent this aliases' },
    'curly': { type: 'style', fixable: true, description: 'Require curly braces' },
    'default-case': { type: 'quality', fixable: false, description: 'Require default case' },
    'default-case-last': { type: 'quality', fixable: false, description: 'Default case last' },
    'default-param-last': { type: 'quality', fixable: false, description: 'Default params last' },
    'dot-notation': { type: 'style', fixable: true, description: 'Prefer dot notation' },
    'eqeqeq': { type: 'quality', fixable: true, description: 'Require === and !==' },
    'func-name-matching': { type: 'style', fixable: false, description: 'Match function name to variable' },
    'func-names': { type: 'style', fixable: false, description: 'Require function names' },
    'func-style': { type: 'style', fixable: false, description: 'Enforce function style' },
    'grouped-accessor-pairs': { type: 'style', fixable: false, description: 'Group getter/setter pairs' },
    'guard-for-in': { type: 'quality', fixable: false, description: 'Guard for-in with hasOwnProperty' },
    'id-denylist': { type: 'style', fixable: false, description: 'Disallow specific identifiers' },
    'id-length': { type: 'style', fixable: false, description: 'Enforce identifier length' },
    'id-match': { type: 'style', fixable: false, description: 'Match identifiers to pattern' },
    'init-declarations': { type: 'style', fixable: false, description: 'Require/disallow init in declarations' },
    'logical-assignment-operators': { type: 'style', fixable: true, description: 'Require logical assignment' },
    'max-classes-per-file': { type: 'maintainability', fixable: false, description: 'Max classes per file' },
    'max-depth': { type: 'maintainability', fixable: false, description: 'Max nesting depth' },
    'max-lines': { type: 'maintainability', fixable: false, description: 'Max lines per file' },
    'max-lines-per-function': { type: 'maintainability', fixable: false, description: 'Max lines per function' },
    'max-nested-callbacks': { type: 'maintainability', fixable: false, description: 'Max callback nesting' },
    'max-params': { type: 'maintainability', fixable: false, description: 'Max function parameters' },
    'max-statements': { type: 'maintainability', fixable: false, description: 'Max statements per function' },
    'multiline-comment-style': { type: 'style', fixable: true, description: 'Multiline comment style' },
    'new-cap': { type: 'style', fixable: false, description: 'Require capitalized constructors' },
    'no-alert': { type: 'quality', fixable: false, description: 'Disallow alert/confirm/prompt' },
    'no-array-constructor': { type: 'quality', fixable: true, description: 'Disallow Array constructor' },
    'no-bitwise': { type: 'quality', fixable: false, description: 'Disallow bitwise operators' },
    'no-caller': { type: 'quality', fixable: false, description: 'Disallow arguments.caller/callee' },
    'no-case-declarations': { type: 'quality', fixable: false, description: 'Disallow lexical declarations in case' },
    'no-console': { type: 'quality', fixable: false, description: 'Disallow console' },
    'no-continue': { type: 'style', fixable: false, description: 'Disallow continue' },
    'no-delete-var': { type: 'quality', fixable: false, description: 'Disallow delete on variables' },
    'no-div-regex': { type: 'quality', fixable: true, description: 'Disallow confusing regex division' },
    'no-else-return': { type: 'style', fixable: true, description: 'Disallow else after return' },
    'no-empty': { type: 'quality', fixable: false, description: 'Disallow empty blocks' },
    'no-empty-function': { type: 'quality', fixable: false, description: 'Disallow empty functions' },
    'no-empty-static-block': { type: 'quality', fixable: false, description: 'Disallow empty static blocks' },
    'no-eq-null': { type: 'quality', fixable: false, description: 'Disallow null comparison' },
    'no-eval': { type: 'security', fixable: false, description: 'Disallow eval()' },
    'no-extend-native': { type: 'quality', fixable: false, description: 'Disallow native prototype extension' },
    'no-extra-bind': { type: 'quality', fixable: true, description: 'Disallow unnecessary bind()' },
    'no-extra-boolean-cast': { type: 'quality', fixable: true, description: 'Disallow unnecessary boolean casts' },
    'no-extra-label': { type: 'quality', fixable: true, description: 'Disallow unnecessary labels' },
    'no-global-assign': { type: 'quality', fixable: false, description: 'Disallow global variable assignment' },
    'no-implicit-coercion': { type: 'style', fixable: true, description: 'Disallow implicit type coercion' },
    'no-implicit-globals': { type: 'quality', fixable: false, description: 'Disallow implicit global variables' },
    'no-implied-eval': { type: 'security', fixable: false, description: 'Disallow implied eval()' },
    'no-inline-comments': { type: 'style', fixable: false, description: 'Disallow inline comments' },
    'no-invalid-this': { type: 'quality', fixable: false, description: 'Disallow invalid this' },
    'no-iterator': { type: 'quality', fixable: false, description: 'Disallow __iterator__' },
    'no-label-var': { type: 'quality', fixable: false, description: 'Disallow label/variable name collision' },
    'no-labels': { type: 'style', fixable: false, description: 'Disallow labeled statements' },
    'no-lone-blocks': { type: 'quality', fixable: false, description: 'Disallow unnecessary blocks' },
    'no-lonely-if': { type: 'style', fixable: true, description: 'Disallow lonely if in else' },
    'no-loop-func': { type: 'quality', fixable: false, description: 'Disallow function creation in loops' },
    'no-magic-numbers': { type: 'maintainability', fixable: false, description: 'Disallow magic numbers' },
    'no-multi-assign': { type: 'style', fixable: false, description: 'Disallow chained assignment' },
    'no-multi-str': { type: 'style', fixable: false, description: 'Disallow multiline strings' },
    'no-negated-condition': { type: 'style', fixable: false, description: 'Disallow negated conditions' },
    'no-nested-ternary': { type: 'style', fixable: false, description: 'Disallow nested ternary' },
    'no-new': { type: 'quality', fixable: false, description: 'Disallow new without assignment' },
    'no-new-func': { type: 'security', fixable: false, description: 'Disallow new Function()' },
    'no-new-wrappers': { type: 'quality', fixable: false, description: 'Disallow primitive wrappers' },
    'no-nonoctal-decimal-escape': { type: 'quality', fixable: false, description: 'Disallow \\8 and \\9' },
    'no-object-constructor': { type: 'quality', fixable: false, description: 'Disallow Object constructor' },
    'no-octal': { type: 'quality', fixable: false, description: 'Disallow octal literals' },
    'no-octal-escape': { type: 'quality', fixable: false, description: 'Disallow octal escapes' },
    'no-param-reassign': { type: 'quality', fixable: false, description: 'Disallow parameter reassignment' },
    'no-plusplus': { type: 'style', fixable: false, description: 'Disallow unary operators' },
    'no-proto': { type: 'quality', fixable: false, description: 'Disallow __proto__' },
    'no-redeclare': { type: 'quality', fixable: false, description: 'Disallow variable redeclaration' },
    'no-regex-spaces': { type: 'style', fixable: true, description: 'Disallow multiple spaces in regex' },
    'no-restricted-exports': { type: 'quality', fixable: false, description: 'Disallow specific exports' },
    'no-restricted-globals': { type: 'quality', fixable: false, description: 'Disallow specific globals' },
    'no-restricted-imports': { type: 'quality', fixable: false, description: 'Disallow specific imports' },
    'no-restricted-properties': { type: 'quality', fixable: false, description: 'Disallow specific properties' },
    'no-restricted-syntax': { type: 'quality', fixable: false, description: 'Disallow specific syntax' },
    'no-return-assign': { type: 'quality', fixable: false, description: 'Disallow assignment in return' },
    'no-script-url': { type: 'security', fixable: false, description: 'Disallow javascript: URLs' },
    'no-sequences': { type: 'quality', fixable: false, description: 'Disallow comma operator' },
    'no-shadow': { type: 'quality', fixable: false, description: 'Disallow variable shadowing' },
    'no-shadow-restricted-names': { type: 'quality', fixable: false, description: 'Disallow shadowing restricted names' },
    'no-ternary': { type: 'style', fixable: false, description: 'Disallow ternary operators' },
    'no-throw-literal': { type: 'quality', fixable: false, description: 'Disallow throwing literals' },
    'no-undef-init': { type: 'style', fixable: true, description: 'Disallow undefined initialization' },
    'no-undefined': { type: 'quality', fixable: false, description: 'Disallow undefined as identifier' },
    'no-underscore-dangle': { type: 'style', fixable: false, description: 'Disallow dangling underscores' },
    'no-unneeded-ternary': { type: 'style', fixable: true, description: 'Disallow unnecessary ternary' },
    'no-unused-expressions': { type: 'quality', fixable: false, description: 'Disallow unused expressions' },
    'no-unused-labels': { type: 'quality', fixable: true, description: 'Disallow unused labels' },
    'no-useless-call': { type: 'quality', fixable: false, description: 'Disallow useless call/apply' },
    'no-useless-catch': { type: 'quality', fixable: false, description: 'Disallow useless catch' },
    'no-useless-computed-key': { type: 'style', fixable: true, description: 'Disallow useless computed keys' },
    'no-useless-concat': { type: 'quality', fixable: false, description: 'Disallow useless string concat' },
    'no-useless-constructor': { type: 'quality', fixable: false, description: 'Disallow useless constructors' },
    'no-useless-escape': { type: 'quality', fixable: true, description: 'Disallow useless escapes' },
    'no-useless-rename': { type: 'style', fixable: true, description: 'Disallow useless import rename' },
    'no-useless-return': { type: 'quality', fixable: true, description: 'Disallow useless return' },
    'no-var': { type: 'quality', fixable: true, description: 'Require let or const' },
    'no-void': { type: 'quality', fixable: false, description: 'Disallow void operator' },
    'no-warning-comments': { type: 'maintainability', fixable: false, description: 'Warn on TODO/FIXME' },
    'no-with': { type: 'quality', fixable: false, description: 'Disallow with statements' },
    'object-shorthand': { type: 'style', fixable: true, description: 'Require object shorthand' },
    'one-var': { type: 'style', fixable: true, description: 'Enforce variable declaration style' },
    'one-var-declaration-per-line': { type: 'style', fixable: true, description: 'One declaration per line' },
    'operator-assignment': { type: 'style', fixable: true, description: 'Require operator assignment' },
    'prefer-arrow-callback': { type: 'style', fixable: true, description: 'Prefer arrow callbacks' },
    'prefer-const': { type: 'quality', fixable: true, description: 'Prefer const for unchanged vars' },
    'prefer-destructuring': { type: 'style', fixable: true, description: 'Prefer destructuring' },
    'prefer-exponentiation-operator': { type: 'style', fixable: true, description: 'Prefer ** over Math.pow' },
    'prefer-named-capture-group': { type: 'style', fixable: false, description: 'Prefer named capture groups' },
    'prefer-numeric-literals': { type: 'style', fixable: true, description: 'Prefer numeric literals' },
    'prefer-object-has-own': { type: 'style', fixable: true, description: 'Prefer Object.hasOwn' },
    'prefer-object-spread': { type: 'style', fixable: true, description: 'Prefer object spread' },
    'prefer-promise-reject-errors': { type: 'quality', fixable: false, description: 'Require Error in reject()' },
    'prefer-regex-literals': { type: 'style', fixable: true, description: 'Prefer regex literals' },
    'prefer-rest-params': { type: 'style', fixable: false, description: 'Prefer rest parameters' },
    'prefer-spread': { type: 'style', fixable: false, description: 'Prefer spread operator' },
    'prefer-template': { type: 'style', fixable: true, description: 'Prefer template literals' },
    'radix': { type: 'quality', fixable: true, description: 'Require radix in parseInt' },
    'require-await': { type: 'quality', fixable: false, description: 'Require await in async' },
    'require-unicode-regexp': { type: 'style', fixable: true, description: 'Require u flag on regex' },
    'require-yield': { type: 'quality', fixable: false, description: 'Require yield in generator' },
    'sort-imports': { type: 'style', fixable: true, description: 'Sort import declarations' },
    'sort-keys': { type: 'style', fixable: false, description: 'Sort object keys' },
    'sort-vars': { type: 'style', fixable: true, description: 'Sort variable declarations' },
    'strict': { type: 'quality', fixable: true, description: 'Require strict mode' },
    'symbol-description': { type: 'quality', fixable: false, description: 'Require Symbol description' },
    'vars-on-top': { type: 'style', fixable: false, description: 'Require var at top of scope' },
    'yoda': { type: 'style', fixable: true, description: 'Require/disallow Yoda conditions' },
};
// =============================================================================
// LAYOUT & FORMATTING - Most deprecated, use @stylistic instead
// =============================================================================
exports.ESLINT_LAYOUT = {
    'unicode-bom': { type: 'style', fixable: true, description: 'Require/disallow BOM' },
};
// =============================================================================
// DEPRECATED RULES - For backwards compatibility
// =============================================================================
exports.ESLINT_DEPRECATED = {
    // Replaced by @stylistic/eslint-plugin
    'array-bracket-newline': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/array-bracket-newline' },
    'array-bracket-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/array-bracket-spacing' },
    'array-element-newline': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/array-element-newline' },
    'arrow-parens': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/arrow-parens' },
    'arrow-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/arrow-spacing' },
    'block-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/block-spacing' },
    'brace-style': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/brace-style' },
    'comma-dangle': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/comma-dangle' },
    'comma-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/comma-spacing' },
    'comma-style': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/comma-style' },
    'computed-property-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/computed-property-spacing' },
    'dot-location': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/dot-location' },
    'eol-last': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/eol-last' },
    'func-call-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/func-call-spacing' },
    'function-call-argument-newline': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/function-call-argument-newline' },
    'function-paren-newline': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/function-paren-newline' },
    'generator-star-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/generator-star-spacing' },
    'implicit-arrow-linebreak': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/implicit-arrow-linebreak' },
    'indent': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/indent' },
    'jsx-quotes': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/jsx-quotes' },
    'key-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/key-spacing' },
    'keyword-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/keyword-spacing' },
    'linebreak-style': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/linebreak-style' },
    'lines-around-comment': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/lines-around-comment' },
    'lines-between-class-members': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/lines-between-class-members' },
    'max-len': { type: 'style', fixable: false, deprecated: true, replacedBy: '@stylistic/max-len' },
    'max-statements-per-line': { type: 'style', fixable: false, deprecated: true, replacedBy: '@stylistic/max-statements-per-line' },
    'multiline-ternary': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/multiline-ternary' },
    'new-parens': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/new-parens' },
    'newline-per-chained-call': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/newline-per-chained-call' },
    'no-extra-parens': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-extra-parens' },
    'no-extra-semi': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-extra-semi' },
    'no-floating-decimal': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-floating-decimal' },
    'no-mixed-operators': { type: 'style', fixable: false, deprecated: true, replacedBy: '@stylistic/no-mixed-operators' },
    'no-mixed-spaces-and-tabs': { type: 'style', fixable: false, deprecated: true, replacedBy: '@stylistic/no-mixed-spaces-and-tabs' },
    'no-multi-spaces': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-multi-spaces' },
    'no-multiple-empty-lines': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-multiple-empty-lines' },
    'no-tabs': { type: 'style', fixable: false, deprecated: true, replacedBy: '@stylistic/no-tabs' },
    'no-trailing-spaces': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-trailing-spaces' },
    'no-whitespace-before-property': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/no-whitespace-before-property' },
    'nonblock-statement-body-position': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/nonblock-statement-body-position' },
    'object-curly-newline': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/object-curly-newline' },
    'object-curly-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/object-curly-spacing' },
    'object-property-newline': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/object-property-newline' },
    'operator-linebreak': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/operator-linebreak' },
    'padded-blocks': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/padded-blocks' },
    'padding-line-between-statements': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/padding-line-between-statements' },
    'quote-props': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/quote-props' },
    'quotes': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/quotes' },
    'rest-spread-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/rest-spread-spacing' },
    'semi': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/semi' },
    'semi-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/semi-spacing' },
    'semi-style': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/semi-style' },
    'space-before-blocks': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/space-before-blocks' },
    'space-before-function-paren': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/space-before-function-paren' },
    'space-in-parens': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/space-in-parens' },
    'space-infix-ops': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/space-infix-ops' },
    'space-unary-ops': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/space-unary-ops' },
    'spaced-comment': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/spaced-comment' },
    'switch-colon-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/switch-colon-spacing' },
    'template-curly-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/template-curly-spacing' },
    'template-tag-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/template-tag-spacing' },
    'wrap-iife': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/wrap-iife' },
    'wrap-regex': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/wrap-regex' },
    'yield-star-spacing': { type: 'style', fixable: true, deprecated: true, replacedBy: '@stylistic/yield-star-spacing' },
    // Node.js replacements
    'callback-return': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'global-require': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'handle-callback-err': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-buffer-constructor': { type: 'security', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-mixed-requires': { type: 'style', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-new-require': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-path-concat': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-process-env': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-process-exit': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-restricted-modules': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
    'no-sync': { type: 'quality', fixable: false, deprecated: true, replacedBy: 'eslint-plugin-n' },
};
// =============================================================================
// COMBINED EXPORT - All ESLint core rules
// =============================================================================
exports.ALL_ESLINT_RULES = {
    ...exports.ESLINT_POSSIBLE_PROBLEMS,
    ...exports.ESLINT_SUGGESTIONS,
    ...exports.ESLINT_LAYOUT,
    ...exports.ESLINT_DEPRECATED,
};
/**
 * Get statistics about ESLint rule coverage
 */
function getESLintRuleStats() {
    const stats = {
        total: 0,
        fixable: 0,
        deprecated: 0,
        byCategory: {},
    };
    for (const rule of Object.values(exports.ALL_ESLINT_RULES)) {
        stats.total++;
        if (rule.fixable)
            stats.fixable++;
        if (rule.deprecated)
            stats.deprecated++;
        stats.byCategory[rule.type] = (stats.byCategory[rule.type] || 0) + 1;
    }
    return stats;
}
