#!/usr/bin/env ts-node
/**
 * Download V9-Generated Assets from Oracle Cloud
 * 
 * Downloads all assets generated by V9 framework:
 * - V9 analysis reports (.md)
 * - Manifest files (.json) with issue metadata
 * - Attachments (fix files for each issue group)
 * 
 * Usage:
 *   npm run download-reports              # Download all reports
 *   npm run download-reports java         # Download Java reports only
 *   npm run download-reports typescript   # Download TypeScript reports only
 *   npm run download-reports --list       # List available reports on server
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const SSH_KEY = process.env.SSH_KEY || '/Users/alpinro/Code Prjects/codequal/keys/oracle/ssh-key-2025-10-07.key';
const ORACLE_IP = process.env.ORACLE_IP || '129.213.49.128';

// Language repositories mapping
const REPOSITORIES = {
  java: [
    'spring-petclinic',
    'spring-boot', 
    'elasticsearch',
    'apache-kafka',
    'micronaut'
  ],
  typescript: [
    'express',
    'vscode',
    'nestjs',
    'angular',
    'nextjs'
  ],
  python: [
    'flask',
    'django',
    'fastapi',
    'pandas',
    'requests'
  ]
};

async function downloadReport(language: string, repository: string): Promise<boolean> {
  const localReportDir = path.join(__dirname, '..', 'tests', 'integration', language, 'v9-reports');
  fs.mkdirSync(localReportDir, { recursive: true });

  const remoteReportPath = `~/codequal/packages/agents/test-outputs/${repository}-v9-report.md`;
  const remoteManifestPath = `~/codequal/packages/agents/test-outputs/${repository}-manifest.json`;
  const localReportPath = path.join(localReportDir, `${repository}-v9-report.md`);
  const localManifestPath = path.join(localReportDir, `${repository}-manifest.json`);

  let reportDownloaded = false;
  let manifestDownloaded = false;

  try {
    console.log(`📥 Downloading ${repository} files...`);
    
    // Download V9 report
    try {
      const checkReportCmd = `ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}" "ls ${remoteReportPath} 2>/dev/null || echo 'NOT_FOUND'"`;
      const reportExists = execSync(checkReportCmd, { encoding: 'utf-8' }).trim();
      
      if (reportExists !== 'NOT_FOUND') {
        const downloadReportCmd = `scp -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}:${remoteReportPath}" "${localReportPath}"`;
        execSync(downloadReportCmd, { stdio: 'pipe' });
        
        if (fs.existsSync(localReportPath)) {
          const stats = fs.statSync(localReportPath);
          console.log(`   ✅ Report: ${repository}-v9-report.md (${(stats.size / 1024).toFixed(1)} KB)`);
          reportDownloaded = true;
        }
      } else {
        console.log(`   ⚠️  Report not found on server`);
      }
    } catch (error) {
      console.log(`   ❌ Report error: ${error.message}`);
    }

    // Download manifest file
    try {
      const checkManifestCmd = `ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}" "ls ${remoteManifestPath} 2>/dev/null || echo 'NOT_FOUND'"`;
      const manifestExists = execSync(checkManifestCmd, { encoding: 'utf-8' }).trim();
      
      if (manifestExists !== 'NOT_FOUND') {
        const downloadManifestCmd = `scp -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}:${remoteManifestPath}" "${localManifestPath}"`;
        execSync(downloadManifestCmd, { stdio: 'pipe' });
        
        if (fs.existsSync(localManifestPath)) {
          const stats = fs.statSync(localManifestPath);
          console.log(`   ✅ Manifest: ${repository}-manifest.json (${(stats.size / 1024).toFixed(1)} KB)`);
          manifestDownloaded = true;
        }
      } else {
        console.log(`   ⚠️  Manifest not found on server`);
      }
    } catch (error) {
      console.log(`   ❌ Manifest error: ${error.message}`);
    }

    // Also download attachments directory if it exists
    try {
      const attachmentsDir = path.join(localReportDir, 'attachments');
      const remoteAttachmentsPath = `~/codequal/packages/agents/test-outputs/${repository}-attachments/`;
      
      const checkAttachmentsCmd = `ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}" "ls -d ${remoteAttachmentsPath} 2>/dev/null || echo 'NOT_FOUND'"`;
      const attachmentsExist = execSync(checkAttachmentsCmd, { encoding: 'utf-8' }).trim();
      
      if (attachmentsExist !== 'NOT_FOUND') {
        fs.mkdirSync(attachmentsDir, { recursive: true });
        const downloadAttachmentsCmd = `scp -r -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}:${remoteAttachmentsPath}*" "${attachmentsDir}/"`;
        execSync(downloadAttachmentsCmd, { stdio: 'pipe' });
        
        const attachmentFiles = fs.readdirSync(attachmentsDir);
        if (attachmentFiles.length > 0) {
          console.log(`   ✅ Attachments: ${attachmentFiles.length} fix files`);
        }
      }
    } catch (error) {
      // Attachments are optional, so just note it
      console.log(`   ℹ️  No attachments found`);
    }

    return reportDownloaded || manifestDownloaded;
  } catch (error) {
    console.log(`   ❌ Error: ${error.message}`);
    return false;
  }
}

async function downloadAllReports(language?: string): Promise<void> {
  console.log('🚀 V9 Report Downloader\n');
  
  const languages = language ? [language] : Object.keys(REPOSITORIES);
  let totalDownloaded = 0;
  let totalFailed = 0;

  for (const lang of languages) {
    console.log(`\n📋 ${lang.toUpperCase()} Reports`);
    console.log('─'.repeat(50));
    
    const repos = REPOSITORIES[lang];
    if (!repos) {
      console.log(`❌ Unknown language: ${lang}`);
      continue;
    }

    for (const repo of repos) {
      const success = await downloadReport(lang, repo);
      if (success) {
        totalDownloaded++;
      } else {
        totalFailed++;
      }
    }
  }

  console.log('\n' + '═'.repeat(50));
  console.log(`📊 Summary: ${totalDownloaded} downloaded, ${totalFailed} failed/missing`);
  
  // List local reports
  console.log('\n📁 Local V9 Reports:');
  for (const lang of languages) {
    const reportDir = path.join(__dirname, '..', 'tests', 'integration', lang, 'v9-reports');
    if (fs.existsSync(reportDir)) {
      const reports = fs.readdirSync(reportDir).filter(f => f.endsWith('.md'));
      if (reports.length > 0) {
        console.log(`\n${lang}:`);
        reports.forEach(r => {
          const filePath = path.join(reportDir, r);
          const stats = fs.statSync(filePath);
          console.log(`  - ${r} (${(stats.size / 1024).toFixed(1)} KB)`);
        });
      }
    }
  }
}

// Alternative: Direct listing of test outputs on Oracle
async function listRemoteReports(): Promise<void> {
  console.log('\n📡 Checking Oracle Cloud for test outputs...\n');
  
  try {
    const listCmd = `ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}" "cd ~/codequal/packages/agents && find . -name '*v9-report.md' -o -name '*-report-*.md' | sort"`;
    const output = execSync(listCmd, { encoding: 'utf-8' });
    
    if (output.trim()) {
      console.log('Found reports:');
      console.log(output);
    } else {
      console.log('No reports found in standard locations.');
      
      // Check test-outputs directory
      console.log('\nChecking test-outputs directory:');
      const testOutputCmd = `ssh -i "${SSH_KEY}" -o StrictHostKeyChecking=no "opc@${ORACLE_IP}" "ls -la ~/codequal/packages/agents/test-outputs/ 2>/dev/null || echo 'Directory not found'"`;
      const testOutput = execSync(testOutputCmd, { encoding: 'utf-8' });
      console.log(testOutput);
    }
  } catch (error) {
    console.error('Error listing remote reports:', error.message);
  }
}

// Main execution
async function main() {
  const args = process.argv.slice(2);
  
  if (args[0] === '--list') {
    await listRemoteReports();
  } else {
    await downloadAllReports(args[0]);
  }
}

main().catch(console.error);
