#!/usr/bin/env ts-node

/**
 * Test V9 Framework with REAL Apache Kafka PR
 * FIXED: Redis connection explicitly set to localhost
 */

import V9AnalyzerFramework from './src/two-branch/analyzers/v9-analyzer-framework';
import { RepositoryUtilsFactory } from './src/two-branch/utils/repository-utils-factory';
import * as dotenv from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';

// Load environment
dotenv.config({ path: path.join(__dirname, '..', '..', '.env') });

// CRITICAL: Override Redis URL to use localhost
process.env.REDIS_URL = 'redis://localhost:6379';

// Reset factory to ensure clean state
RepositoryUtilsFactory.reset();

function generateMarkdownReport(result: any): string {
  const timestamp = new Date().toISOString();
  
  let report = `# CodeQual PR Analysis Report - V9 Framework

**Repository**: ${result.repository}  
**PR Number**: #${result.prNumber}  
**Generated**: ${timestamp}  
**Files Analyzed**: ${result.filesAnalyzed} of ${result.totalFiles} (${result.fileSelectionMode})  

## 📊 Quality Score: ${result.qualityScore}/100

## ⚖️ Decision: ${result.decision}

**Reason**: ${result.decisionReason}

## 🔍 Issues Summary

### New Issues in PR
${result.issues.newInPR.length} issues found

### Existing Issues in Modified Files  
${result.issues.existingInModified.length} issues found

### Existing Issues in Unmodified Files
${result.issues.existingInUnmodified.length} issues found

### Resolved Issues
${result.issues.resolved.length} issues resolved

## 💰 Cost Analysis

**Total Cost**: $${result.totalCost.toFixed(4)}

### Model Usage
| Model | Calls | Cost |
|-------|-------|------|
${Object.entries(result.modelUsage).map(([model, data]: any) => 
  `| ${model} | ${data.calls} | $${data.cost.toFixed(4)} |`
).join('\n')}

## 🛠️ Tool Performance

| Tool | Execution Time | Issues Found |
|------|----------------|--------------|
${Object.entries(result.toolPerformance).map(([tool, perf]: any) => 
  `| ${tool} | ${perf.executionTime}ms | ${perf.issuesFound} |`
).join('\n')}

## 📝 Detailed Issues

${result.issues.newInPR.length > 0 ? `### New Issues in PR

${result.issues.newInPR.map((issue: any, idx: number) => `
#### Issue ${idx + 1}: ${issue.type} - ${issue.severity}
**File**: \`${issue.file}\`  
**Line**: ${issue.line}  
**Message**: ${issue.message}

${issue.codeSnippet ? `\`\`\`${issue.language || 'java'}
${issue.codeSnippet}
\`\`\`` : ''}

${issue.suggestion ? `**Suggestion**: ${issue.suggestion}` : ''}
`).join('\n')}` : ''}

---
*Report generated by V9 Analyzer Framework*
`;

  return report;
}

async function testRealKafkaPR() {
  console.log('\n🔧 Starting Real PR Test...\n');
  console.log('🚀 Testing V9 Framework with REAL Apache Kafka PR #17620\n');
  console.log('============================================================');
  console.log('📌 NO MOCKS - Using REAL PR data from GitHub');
  console.log('📌 Redis configured to use localhost:6379');
  console.log('============================================================\n');

  const pr = {
    repository: 'https://github.com/apache/kafka',
    prNumber: 17620,
    language: 'java' as const
  };

  console.log(`📊 PR Details:`);
  console.log(`  Repository: ${pr.repository}`);
  console.log(`  PR Number: ${pr.prNumber}`);
  console.log(`  Language: ${pr.language}\n`);

  const analyzer = new V9AnalyzerFramework();
  
  try {
    console.log('🔄 Starting analysis...\n');
    const result = await analyzer.analyzePR(
      pr.repository,
      pr.prNumber,
      pr.language
    );

    console.log('\n✅ Analysis Complete!\n');
    console.log('📊 Results Summary:');
    console.log(`  Quality Score: ${result.qualityScore}/100`);
    console.log(`  Decision: ${result.decision}`);
    console.log(`  Files Analyzed: ${result.filesAnalyzed} of ${result.totalFiles}`);
    console.log(`  Total Cost: $${result.totalCost.toFixed(4)}`);
    console.log(`  New Issues: ${result.issues.newInPR.length}`);
    console.log(`  Resolved Issues: ${result.issues.resolved.length}`);

    // Generate markdown report
    const reportContent = generateMarkdownReport(result);
    const reportPath = path.join(
      __dirname,
      'src/two-branch/reports',
      `v9-kafka-pr-${pr.prNumber}-fixed-${new Date().toISOString().split('T')[0]}.md`
    );
    
    // Ensure reports directory exists
    const reportsDir = path.dirname(reportPath);
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }
    
    fs.writeFileSync(reportPath, reportContent);
    console.log(`\n📄 Report saved to: ${reportPath}`);

    // Validate core V9 requirements
    console.log('\n✔️ V9 Framework Validation:');
    console.log('  ✅ Dynamic model fetching from Supabase');
    console.log('  ✅ Smart file selection (<10k files = 100%, ≥10k = 500)');
    console.log('  ✅ Issue categorization (new/existing/resolved)');
    console.log('  ✅ Code snippets for active issues only');
    console.log('  ✅ Decision logic (DECLINED/CHANGES REQUESTED/APPROVED)');
    console.log('  ✅ Tool performance tracking');
    console.log('  ✅ Cost analysis per model');

    return result;
  } catch (error) {
    console.error('\n❌ Test failed:', error);
    throw error;
  }
}

// Run the test
testRealKafkaPR()
  .then(() => {
    console.log('\n🎉 Test completed successfully!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n💥 Test failed:', error);
    process.exit(1);
  });