/**
 * Cloud API Tool Orchestrator
 *
 * Manages execution of cloud-based API tools (Corgea, etc.) with:
 * - Subscription tier gating (BASIC vs PRO)
 * - Async parallel execution with CLI tools
 * - Rate limit management
 * - Result aggregation
 *
 * Integration with 3-Tier Fix Flow:
 * - Tier 1: Native --fix (eslint --fix, etc.)
 * - Tier 2: Dedicated fixers (eslint-fix, pmd-fix)
 * - Tier 2.5: Cloud API fixers (Corgea) <- NEW
 * - Tier 3: AI-only recommendations
 *
 * @since Session 60
 */

import { Issue } from '../../analyzers/v9-types';
import { GeneratedFix, RateLimitInfo, APIErrorCode } from './base-api-tool';
import { CorgeaFixer, CorgeaFix, createCorgeaFixer, isCorgeaEnabled } from './corgea-fixer';

// ============================================================
// TYPES
// ============================================================

export type SubscriptionTier = 'basic' | 'pro' | 'enterprise';

export interface CloudAPIOptions {
  /** User's subscription tier */
  tier: SubscriptionTier;

  /** Issues that need fixes */
  issues: Issue[];

  /** Source code for context (optional, improves fix quality) */
  sourceCode?: Map<string, string>;

  /** Programming language */
  language: string;

  /** Repository URL */
  repositoryUrl?: string;

  /** Branch name */
  branch?: string;

  /** Run cloud API tools in parallel with CLI tools */
  runInParallel?: boolean;

  /** Only fix issues above this severity */
  minSeverity?: 'low' | 'medium' | 'high' | 'critical';

  /** Maximum fixes to generate (for cost control) */
  maxFixes?: number;

  /** Skip cloud API tools even if available */
  skipCloudTools?: boolean;
}

export interface CloudAPIResult {
  /** Whether cloud API tools were executed */
  executed: boolean;

  /** Why cloud tools were skipped (if not executed) */
  skipReason?: string;

  /** Total execution duration */
  duration: number;

  /** Fixes generated by cloud APIs */
  fixes: GeneratedFix[];

  /** Errors encountered */
  errors: CloudAPIError[];

  /** Rate limit info after execution */
  rateLimitInfo?: RateLimitInfo;

  /** Cost estimate for this execution */
  estimatedCost?: number;
}

export interface CloudAPIError {
  tool: string;
  message: string;
  code: APIErrorCode;
  retryable: boolean;
}

// ============================================================
// TIER CONFIGURATION
// ============================================================

/**
 * Features available by subscription tier
 */
const TIER_FEATURES: Record<SubscriptionTier, TierFeatures> = {
  basic: {
    cloudFixersEnabled: false,
    maxFixesPerAnalysis: 0,
    maxMonthlyFixes: 0,
    priorityQueue: false
  },
  pro: {
    cloudFixersEnabled: true,
    maxFixesPerAnalysis: 50,
    maxMonthlyFixes: 500,
    priorityQueue: false
  },
  enterprise: {
    cloudFixersEnabled: true,
    maxFixesPerAnalysis: 200,
    maxMonthlyFixes: -1, // Unlimited
    priorityQueue: true
  }
};

interface TierFeatures {
  cloudFixersEnabled: boolean;
  maxFixesPerAnalysis: number;
  maxMonthlyFixes: number;
  priorityQueue: boolean;
}

// ============================================================
// ORCHESTRATOR CLASS
// ============================================================

export class CloudAPIOrchestrator {
  private corgeaFixer: CorgeaFixer | null = null;
  private initialized = false;

  constructor() {
    // Lazy initialization to avoid issues if env vars not set
  }

  /**
   * Initialize cloud API connections
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    // Initialize Corgea if configured
    if (isCorgeaEnabled()) {
      this.corgeaFixer = createCorgeaFixer();

      if (this.corgeaFixer) {
        const healthy = await this.corgeaFixer.checkHealth();
        if (!healthy) {
          console.warn('[CloudAPI] Corgea health check failed - disabling');
          this.corgeaFixer = null;
        }
      }
    }

    this.initialized = true;
  }

  /**
   * Execute cloud API tools for fix generation
   */
  async execute(options: CloudAPIOptions): Promise<CloudAPIResult> {
    const startTime = Date.now();
    const errors: CloudAPIError[] = [];
    const allFixes: GeneratedFix[] = [];

    // Check if cloud tools should be skipped
    const skipCheck = this.shouldSkip(options);
    if (skipCheck.skip) {
      return {
        executed: false,
        skipReason: skipCheck.reason,
        duration: Date.now() - startTime,
        fixes: [],
        errors: []
      };
    }

    // Ensure initialized
    await this.initialize();

    // Get tier features
    const tierFeatures = TIER_FEATURES[options.tier];

    // Apply fix limits
    const maxFixes = Math.min(
      options.maxFixes || Infinity,
      tierFeatures.maxFixesPerAnalysis
    );

    // Execute Corgea if available
    if (this.corgeaFixer) {
      try {
        const result = await this.corgeaFixer.execute({
          issues: options.issues,
          sourceCode: options.sourceCode,
          language: options.language,
          repositoryUrl: options.repositoryUrl,
          branch: options.branch,
          minSeverity: options.minSeverity,
          maxFixes
        });

        if (result.success && result.fixes) {
          allFixes.push(...result.fixes);
        } else if (!result.success) {
          errors.push({
            tool: 'Corgea',
            message: result.error || 'Unknown error',
            code: result.errorCode || APIErrorCode.UNKNOWN,
            retryable: result.errorCode === APIErrorCode.RATE_LIMITED ||
                       result.errorCode === APIErrorCode.TIMEOUT
          });
        }

      } catch (error) {
        errors.push({
          tool: 'Corgea',
          message: (error as Error).message,
          code: APIErrorCode.UNKNOWN,
          retryable: false
        });
      }
    }

    // Get rate limit info
    let rateLimitInfo: RateLimitInfo | undefined;
    if (this.corgeaFixer) {
      try {
        rateLimitInfo = await this.corgeaFixer.getRateLimitStatus();
      } catch {
        // Ignore rate limit check errors
      }
    }

    return {
      executed: true,
      duration: Date.now() - startTime,
      fixes: allFixes,
      errors,
      rateLimitInfo,
      estimatedCost: this.estimateCost(allFixes.length)
    };
  }

  /**
   * Check if cloud tools should be skipped
   */
  private shouldSkip(options: CloudAPIOptions): { skip: boolean; reason?: string } {
    // Explicit skip requested
    if (options.skipCloudTools) {
      return { skip: true, reason: 'Explicitly skipped' };
    }

    // Check tier
    const tierFeatures = TIER_FEATURES[options.tier];
    if (!tierFeatures.cloudFixersEnabled) {
      return {
        skip: true,
        reason: `Cloud fixers not available on ${options.tier} tier (upgrade to PRO)`
      };
    }

    // Check if any cloud tools are configured
    if (!isCorgeaEnabled()) {
      return { skip: true, reason: 'No cloud API tools configured' };
    }

    // Check if there are any issues to fix
    if (!options.issues || options.issues.length === 0) {
      return { skip: true, reason: 'No issues to fix' };
    }

    return { skip: false };
  }

  /**
   * Estimate cost for fix generation
   * (Corgea is free, but track for future paid tools)
   */
  private estimateCost(fixCount: number): number {
    // Corgea is currently free
    // This is a placeholder for future paid tools
    return 0;
  }

  /**
   * Check if cloud API tools are available for the given tier
   */
  isAvailable(tier: SubscriptionTier): boolean {
    const features = TIER_FEATURES[tier];
    return features.cloudFixersEnabled && (isCorgeaEnabled());
  }

  /**
   * Get configured cloud tools
   */
  getConfiguredTools(): string[] {
    const tools: string[] = [];

    if (isCorgeaEnabled()) {
      tools.push('corgea');
    }

    return tools;
  }

  /**
   * Get tier features for display
   */
  getTierFeatures(tier: SubscriptionTier): TierFeatures {
    return TIER_FEATURES[tier];
  }
}

// ============================================================
// SINGLETON INSTANCE
// ============================================================

let orchestratorInstance: CloudAPIOrchestrator | null = null;

/**
 * Get the singleton cloud API orchestrator instance
 */
export function getCloudAPIOrchestrator(): CloudAPIOrchestrator {
  if (!orchestratorInstance) {
    orchestratorInstance = new CloudAPIOrchestrator();
  }
  return orchestratorInstance;
}

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Execute cloud fixers and merge results with CLI fixer results
 *
 * This is the main integration point with the 3-tier fix flow.
 * Call this after Tier 2 (dedicated fixers) and before Tier 3 (AI-only).
 */
export async function executeCloudFixers(
  issues: Issue[],
  options: {
    tier: SubscriptionTier;
    language: string;
    sourceCode?: Map<string, string>;
    repositoryUrl?: string;
    branch?: string;
    existingFixes?: GeneratedFix[]; // Fixes from Tier 1/2
  }
): Promise<{
  fixes: GeneratedFix[];
  cloudResult: CloudAPIResult;
}> {
  const orchestrator = getCloudAPIOrchestrator();

  // Filter out issues that already have fixes from Tier 1/2
  const existingFixIds = new Set(options.existingFixes?.map(f => f.issueId) || []);
  const unfixedIssues = issues.filter(issue => {
    const issueId = `${issue.rule}-${issue.file}-${issue.line}`;
    return !existingFixIds.has(issueId);
  });

  // Execute cloud fixers on unfixed issues
  const cloudResult = await orchestrator.execute({
    tier: options.tier,
    issues: unfixedIssues,
    sourceCode: options.sourceCode,
    language: options.language,
    repositoryUrl: options.repositoryUrl,
    branch: options.branch
  });

  // Merge fixes (Tier 1/2 + Cloud API)
  const allFixes = [
    ...(options.existingFixes || []),
    ...cloudResult.fixes
  ];

  return {
    fixes: allFixes,
    cloudResult
  };
}

/**
 * Check if cloud fixers can provide value for the given issues
 */
export function canCloudFixersHelp(
  issues: Issue[],
  tier: SubscriptionTier
): { canHelp: boolean; reason: string; potentialFixes: number } {
  const orchestrator = getCloudAPIOrchestrator();

  if (!orchestrator.isAvailable(tier)) {
    return {
      canHelp: false,
      reason: tier === 'basic'
        ? 'Upgrade to PRO for AI-powered fixes'
        : 'Cloud fixers not configured',
      potentialFixes: 0
    };
  }

  // Count issues that could benefit from cloud fixes
  // (security issues, complex bugs, etc.)
  const cloudFixableCategories = ['security', 'bugs', 'vulnerability'];
  const potentialFixes = issues.filter(issue =>
    cloudFixableCategories.includes(issue.category?.toLowerCase() || '')
  ).length;

  if (potentialFixes === 0) {
    return {
      canHelp: false,
      reason: 'No issues suitable for AI-powered fixes',
      potentialFixes: 0
    };
  }

  return {
    canHelp: true,
    reason: `${potentialFixes} issues can be fixed by Corgea AI`,
    potentialFixes
  };
}
