/**
 * Base Cloud API Tool
 *
 * Abstract base class for cloud-based security analysis APIs.
 * Provides common functionality for HTTP communication, authentication,
 * rate limiting, and error handling.
 *
 * Key Features:
 * - Token-based authentication (Bearer)
 * - Automatic retry with exponential backoff
 * - Rate limit tracking and respect
 * - Timeout handling
 * - Structured error responses
 *
 * @since Session 60
 */

import { Issue } from '../../analyzers/v9-types';

// ============================================================
// CONFIGURATION TYPES
// ============================================================

export interface CloudAPIConfig {
  /** Tool name for logging */
  name: string;

  /** Base URL of the API (e.g., https://api.corgea.app) */
  baseUrl: string;

  /** API key or token for authentication */
  apiKey: string;

  /** Custom auth header name (default: uses 'Authorization: Bearer <key>') */
  authHeaderName?: string;

  /** Request timeout in milliseconds (default: 300000 = 5 min) */
  timeout?: number;

  /** Number of retry attempts on failure (default: 3) */
  retries?: number;

  /** Delay between retries in ms (default: 1000, uses exponential backoff) */
  retryDelay?: number;
}

// ============================================================
// RESULT TYPES
// ============================================================

export interface APIToolResult {
  /** Whether the API call succeeded */
  success: boolean;

  /** Total duration of the operation in milliseconds */
  duration: number;

  /** Issues returned by the API (for scanners) */
  issues?: Issue[];

  /** Fixes generated by the API (for fixers) */
  fixes?: GeneratedFix[];

  /** Error message if success is false */
  error?: string;

  /** Error code for categorization */
  errorCode?: APIErrorCode;

  /** Remaining API calls before rate limit */
  rateLimitRemaining?: number;

  /** When rate limit resets (Unix timestamp) */
  rateLimitReset?: number;
}

export interface GeneratedFix {
  /** Reference to the original issue */
  issueId: string;

  /** Original rule/check ID */
  ruleId: string;

  /** File path relative to repository root */
  file: string;

  /** Line number of the issue */
  line: number;

  /** Original code snippet */
  originalCode: string;

  /** Fixed code snippet */
  fixedCode: string;

  /** AI-generated explanation of the fix */
  explanation: string;

  /** Confidence score (0-100) */
  confidence: number;

  /** Whether fix is safe for auto-apply */
  safeForAutoApply: boolean;

  /** Diff in unified format */
  diff?: string;
}

export interface RateLimitInfo {
  /** Total requests allowed per window */
  limit: number;

  /** Remaining requests in current window */
  remaining: number;

  /** When the window resets (Unix timestamp) */
  resetAt: number;

  /** Window duration in seconds */
  windowSeconds: number;
}

// ============================================================
// ERROR TYPES
// ============================================================

export enum APIErrorCode {
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  RATE_LIMITED = 'RATE_LIMITED',
  TIMEOUT = 'TIMEOUT',
  INVALID_REQUEST = 'INVALID_REQUEST',
  SERVER_ERROR = 'SERVER_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  PARSE_ERROR = 'PARSE_ERROR',
  UNKNOWN = 'UNKNOWN'
}

export class CloudAPIError extends Error {
  constructor(
    message: string,
    public code: APIErrorCode,
    public statusCode?: number,
    public retryable: boolean = false
  ) {
    super(message);
    this.name = 'CloudAPIError';
  }
}

// ============================================================
// BASE CLASS
// ============================================================

/**
 * Abstract base class for cloud API tools.
 * Handles HTTP communication, authentication, and error handling.
 */
export abstract class CloudAPIToolBase {
  protected config: CloudAPIConfig;

  constructor(config: CloudAPIConfig) {
    this.config = {
      timeout: 300000,
      retries: 3,
      retryDelay: 1000,
      ...config
    };
  }

  /**
   * Execute the tool's primary operation
   * Must be implemented by subclasses
   */
  abstract execute(input: unknown): Promise<APIToolResult>;

  /**
   * Check if the API is reachable and credentials are valid
   */
  abstract checkHealth(): Promise<boolean>;

  /**
   * Get current rate limit status
   */
  abstract getRateLimitStatus(): Promise<RateLimitInfo>;

  /**
   * Make an HTTP request with retry logic
   */
  protected async makeRequest<T>(
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD',
    endpoint: string,
    data?: unknown,
    options?: RequestOptions
  ): Promise<APIResponse<T>> {
    const url = `${this.config.baseUrl}${endpoint}`;
    const timeout = options?.timeout || this.config.timeout!;
    const maxRetries = options?.retries ?? this.config.retries!;

    let lastError: Error | null = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), timeout);

        // Build auth header based on config
        const authHeader = this.config.authHeaderName
          ? { [this.config.authHeaderName]: this.config.apiKey }
          : { 'Authorization': `Bearer ${this.config.apiKey}` };

        const response = await fetch(url, {
          method,
          headers: {
            ...authHeader,
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'User-Agent': 'CodeQual/1.0',
            ...options?.headers
          },
          body: data ? JSON.stringify(data) : undefined,
          signal: controller.signal
        });

        clearTimeout(timeoutId);

        // Extract rate limit headers
        const rateLimitInfo = this.extractRateLimitHeaders(response.headers);

        // Handle non-2xx responses
        if (!response.ok) {
          const error = await this.handleErrorResponse(response);

          // Retry on certain errors
          if (error.retryable && attempt < maxRetries) {
            const delay = this.calculateBackoff(attempt);
            console.log(`[${this.config.name}] Retrying in ${delay}ms (attempt ${attempt + 1}/${maxRetries})`);
            await this.sleep(delay);
            continue;
          }

          throw error;
        }

        // Parse response
        const responseData = await response.json() as T;

        return {
          data: responseData,
          status: response.status,
          rateLimitInfo
        };

      } catch (error: unknown) {
        if (error instanceof CloudAPIError) {
          lastError = error;
          if (!error.retryable || attempt >= maxRetries) {
            throw error;
          }
        } else if (error instanceof Error) {
          if (error.name === 'AbortError') {
            lastError = new CloudAPIError(
              `Request timed out after ${timeout}ms`,
              APIErrorCode.TIMEOUT,
              undefined,
              true
            );
          } else {
            lastError = new CloudAPIError(
              `Network error: ${error.message}`,
              APIErrorCode.NETWORK_ERROR,
              undefined,
              true
            );
          }

          if (attempt < maxRetries) {
            const delay = this.calculateBackoff(attempt);
            console.log(`[${this.config.name}] Retrying in ${delay}ms (attempt ${attempt + 1}/${maxRetries})`);
            await this.sleep(delay);
            continue;
          }
        }
      }
    }

    throw lastError || new CloudAPIError('Unknown error', APIErrorCode.UNKNOWN);
  }

  /**
   * Extract rate limit info from response headers
   */
  protected extractRateLimitHeaders(headers: Headers): RateLimitInfo | undefined {
    const limit = headers.get('X-RateLimit-Limit');
    const remaining = headers.get('X-RateLimit-Remaining');
    const reset = headers.get('X-RateLimit-Reset');

    if (limit && remaining && reset) {
      return {
        limit: parseInt(limit, 10),
        remaining: parseInt(remaining, 10),
        resetAt: parseInt(reset, 10),
        windowSeconds: 3600 // Default 1 hour window
      };
    }

    return undefined;
  }

  /**
   * Handle error responses from the API
   */
  protected async handleErrorResponse(response: Response): Promise<CloudAPIError> {
    let message = `API error: ${response.status} ${response.statusText}`;
    let code = APIErrorCode.UNKNOWN;
    let retryable = false;

    try {
      const errorBody = await response.json() as { message?: string; error?: string };
      message = errorBody.message || errorBody.error || message;
    } catch {
      // Ignore JSON parse errors for error responses
    }

    switch (response.status) {
      case 401:
      case 403:
        code = APIErrorCode.AUTHENTICATION_FAILED;
        message = 'Authentication failed - check API key';
        break;
      case 429:
        code = APIErrorCode.RATE_LIMITED;
        message = 'Rate limit exceeded - try again later';
        retryable = true;
        break;
      case 400:
        code = APIErrorCode.INVALID_REQUEST;
        break;
      case 500:
      case 502:
      case 503:
      case 504:
        code = APIErrorCode.SERVER_ERROR;
        retryable = true;
        break;
    }

    return new CloudAPIError(message, code, response.status, retryable);
  }

  /**
   * Calculate exponential backoff delay
   */
  protected calculateBackoff(attempt: number): number {
    const baseDelay = this.config.retryDelay!;
    const maxDelay = 30000; // 30 seconds max
    const delay = Math.min(baseDelay * Math.pow(2, attempt), maxDelay);
    // Add jitter (0-25% of delay)
    return delay + Math.random() * delay * 0.25;
  }

  /**
   * Sleep for specified milliseconds
   */
  protected sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /**
   * Log with tool name prefix
   */
  protected log(message: string, level: 'info' | 'warn' | 'error' = 'info'): void {
    const prefix = `[CloudAPI:${this.config.name}]`;
    switch (level) {
      case 'error':
        console.error(`${prefix} ${message}`);
        break;
      case 'warn':
        console.warn(`${prefix} ${message}`);
        break;
      default:
        console.log(`${prefix} ${message}`);
    }
  }
}

// ============================================================
// HELPER TYPES
// ============================================================

interface RequestOptions {
  timeout?: number;
  retries?: number;
  headers?: Record<string, string>;
}

interface APIResponse<T> {
  data: T;
  status: number;
  rateLimitInfo?: RateLimitInfo;
}
