# IMPORTANT: Copy this file to secrets.yaml and fill in actual values
# DO NOT commit secrets.yaml to version control!
apiVersion: v1
kind: Secret
metadata:
  name: codequal-secrets
  namespace: codequal-prod
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgresql://doadmin:CHANGE_ME@db-postgresql-nyc1-xxxxx.b.db.ondigitalocean.com:25060/codequal?sslmode=require"
  
  # Supabase
  SUPABASE_URL: "https://your-project.supabase.co"
  SUPABASE_SERVICE_KEY: "your-service-key"
  SUPABASE_ANON_KEY: "your-anon-key"
  SUPABASE_JWT_SECRET: "your-jwt-secret"
  
  # OpenAI
  OPENAI_API_KEY: "sk-..."
  
  # GitHub App
  GITHUB_APP_ID: "your-app-id"
  GITHUB_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_PRIVATE_KEY_HERE
    -----END RSA PRIVATE KEY-----
  GITHUB_WEBHOOK_SECRET: "your-webhook-secret"
  
  # Application
  NODE_ENV: "production"
  API_SECRET_KEY: "generate-a-secure-random-string"
  
  # Monitoring
  GRAFANA_API_KEY: "your-grafana-key"
  
  # Email (if using)
  RESEND_API_KEY: "re_..."
  
  # Stripe (when ready)
  STRIPE_SECRET_KEY: "sk_live_..."
  STRIPE_WEBHOOK_SECRET: "whsec_..."