apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepwiki-data
  namespace: codequal-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi