apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepwiki-data-new
  namespace: codequal-dev
  labels:
    app: deepwiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  # Increased from current size
