apiVersion: v1
kind: Secret
metadata:
  name: deepwiki-env-fixed
  namespace: codequal-dev
type: Opaque
data:
  # Use the correct keys (base64 encoded)
  OPENAI_API_KEY: c2stcHJvai1CSTcyb3JDdlZ2MENGRmJzNGxma0lCVWg5aXFpT0lFLXlxZ0UzWWczLXhzMGdRVml6dGFUQnBEYlhIbEdmRjZJclVlY3cwVlBvNlQzQmxia0ZKdW9SdjRGdjJYWENSWlF4ZWR5MUNnV1V4Q0dmRkdzWlhVTE5aRGxWTm04VUVvSkNsRGlOQjd0WDlYSjQ4UjJHYkt4czdrclFoY0E=
  GOOGLE_API_KEY: QUl6YVN5QXg1TWo2WXRyZ25pdmt4VUdxekFpMWhfUXhUWDBITldR
  ANTHROPIC_API_KEY: c2stYW50LWFwaTAzLVBVblJaX2ZFMENVYTJyd3h2eWI5ODJvRFdxc0VTVmZqOHoyU3VYMEFLN3VjdkljUV94LVp2S1doaVNVLXdsZ0xISThobmlJcTNRc3FlNTI4ZVZMdHpnLUZESTBLd0FB
  DEEPSEEK_API_KEY: c2stZDUxM2RlM2Y2NTBlNDQ5N2IwYjY3ZDU0MmIyYWQxOTA=
  # Add specific provider configurations
  PROVIDER_CONFIG_OPENAI: ZW5hYmxlZDogdHJ1ZQ==  # enabled: true
  PROVIDER_CONFIG_ANTHROPIC: ZW5hYmxlZDogdHJ1ZQ==  # enabled: true
  PROVIDER_CONFIG_GOOGLE: ZW5hYmxlZDogdHJ1ZQ==    # enabled: true
  PROVIDER_CONFIG_DEEPSEEK: ZW5hYmxlZDogdHJ1ZQ==  # enabled: true
  # Add debug mode to show more detailed logs
  DEBUG: dHJ1ZQ==  # true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepwiki-data-large
  namespace: codequal-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepwiki-fixed
  namespace: codequal-dev
  labels:
    app: deepwiki-fixed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepwiki-fixed
  template:
    metadata:
      labels:
        app: deepwiki-fixed
    spec:
      containers:
      - name: deepwiki
        image: ghcr.io/asyncfuncai/deepwiki-open:latest
        ports:
        - containerPort: 8001
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: deepwiki-env-fixed
        env:
        - name: SERVER_BASE_URL
          value: http://deepwiki-fixed:8001
        - name: NEXT_PUBLIC_SERVER_BASE_URL
          value: http://deepwiki-fixed:8001
        volumeMounts:
        - name: deepwiki-data
          mountPath: /root/.adalflow
      volumes:
      - name: deepwiki-data
        persistentVolumeClaim:
          claimName: deepwiki-data-large
---
apiVersion: v1
kind: Service
metadata:
  name: deepwiki-fixed
  namespace: codequal-dev
spec:
  selector:
    app: deepwiki-fixed
  ports:
  - port: 8001
    targetPort: 8001
    name: api
  - port: 80
    targetPort: 3000
    name: frontend
