/**
 * PR Summary Comment Generator
 *
 * Session 85: Generate concise, actionable PR summary comments
 * for GitHub/GitLab integration.
 *
 * Supports two tiers:
 * - BASIC: Educational focus, patterns + guidance, no AI fixes shown
 * - PRO: Fix-focused with before/after, confidence scores, CLI commands
 */

export interface PRSummaryInput {
  /** Repository name */
  repository: string;
  /** PR number */
  prNumber: number;
  /** PR title */
  prTitle: string;
  /** PR author */
  author: string;
  /** Analysis tier */
  tier: 'basic' | 'pro' | 'enterprise';
  /** Total issues found */
  totalIssues: number;
  /** Issues by severity */
  severityCounts: {
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  /** Issues by category */
  categoryCounts: {
    security: number;
    performance: number;
    architecture: number;
    dependencies: number;
    codeQuality: number;
  };
  /** Score information */
  score: {
    overall: number;
    grade: string;
  };
  /** Blocking decision */
  blocking: {
    isBlocking: boolean;
    blockingCount: number;
  };
  /** Fix information (PRO tier) */
  fixes?: {
    autoFixed: number;
    pendingReview: number;
    alreadyResolved: number;
  };
  /** Files changed */
  filesChanged: number;
  /** Lines added/removed */
  linesChanged: {
    added: number;
    removed: number;
  };
  /** Platform coverage (if multi-platform) */
  platforms?: string[];
  /** Report URL */
  reportUrl?: string;
  /** SARIF URL */
  sarifUrl?: string;
}

/**
 * Generate BASIC tier PR summary comment
 *
 * Focus: Educational, patterns, IDE integration guidance
 * No AI-generated code shown
 */
export function generateBasicPRSummary(input: PRSummaryInput): string {
  const {
    repository,
    prNumber,
    prTitle,
    author,
    totalIssues,
    severityCounts,
    categoryCounts,
    score,
    blocking,
    filesChanged,
    linesChanged,
    platforms,
    reportUrl,
    sarifUrl,
  } = input;

  const lines: string[] = [];

  // Header
  lines.push(`## CodeQual Analysis Report`);
  lines.push('');

  // Quick summary
  const emoji = blocking.isBlocking ? ':x:' : (totalIssues > 0 ? ':warning:' : ':white_check_mark:');
  const decision = blocking.isBlocking
    ? `**${blocking.blockingCount} blocking issues** require fixes before merge`
    : (totalIssues > 0 ? `${totalIssues} issues found (non-blocking)` : 'No issues found');

  lines.push(`${emoji} ${decision}`);
  lines.push('');

  // Score badge
  lines.push(`**Score:** ${score.overall}/100 (Grade: **${score.grade}**)`);
  lines.push('');

  // Change summary
  lines.push('### Change Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Files Changed | ${filesChanged} |`);
  lines.push(`| Lines | +${linesChanged.added} / -${linesChanged.removed} |`);
  if (platforms && platforms.length > 1) {
    lines.push(`| Platforms | ${platforms.join(', ')} |`);
  }
  lines.push('');

  // Issue breakdown (if any)
  if (totalIssues > 0) {
    lines.push('### Issues Found');
    lines.push('');
    lines.push('| Severity | Count |');
    lines.push('|----------|-------|');
    if (severityCounts.critical > 0) lines.push(`| :red_circle: Critical | ${severityCounts.critical} |`);
    if (severityCounts.high > 0) lines.push(`| :orange_circle: High | ${severityCounts.high} |`);
    if (severityCounts.medium > 0) lines.push(`| :yellow_circle: Medium | ${severityCounts.medium} |`);
    if (severityCounts.low > 0) lines.push(`| :green_circle: Low | ${severityCounts.low} |`);
    lines.push('');

    // Category breakdown
    const categories = Object.entries(categoryCounts).filter(([_, count]) => count > 0);
    if (categories.length > 0) {
      lines.push('**By Category:**');
      categories.forEach(([cat, count]) => {
        const icon = getCategoryIcon(cat);
        lines.push(`- ${icon} ${formatCategory(cat)}: ${count}`);
      });
      lines.push('');
    }
  }

  // Actions section
  lines.push('### Quick Actions');
  lines.push('');
  lines.push('**IDE Integration:**');
  lines.push('- Download SARIF file for VS Code/JetBrains one-click fixes');
  lines.push('- Use CodeQual LSP for inline suggestions');
  lines.push('');

  // Links
  if (reportUrl || sarifUrl) {
    lines.push('**Resources:**');
    if (reportUrl) lines.push(`- [:page_facing_up: Full Report](${reportUrl})`);
    if (sarifUrl) lines.push(`- [:file_folder: SARIF Export](${sarifUrl})`);
    lines.push('');
  }

  // Upgrade prompt
  lines.push('---');
  lines.push('');
  lines.push(':star: **Upgrade to PRO** for AI-powered auto-fixes with before/after comparisons');
  lines.push('');

  // Footer
  lines.push('<sub>Generated by [CodeQual](https://codequal.dev) | BASIC Tier</sub>');

  return lines.join('\n');
}

/**
 * Generate PRO tier PR summary comment
 *
 * Focus: Fix results, before/after, confidence, CLI commands
 */
export function generateProPRSummary(input: PRSummaryInput): string {
  const {
    repository,
    prNumber,
    prTitle,
    author,
    totalIssues,
    severityCounts,
    categoryCounts,
    score,
    blocking,
    fixes,
    filesChanged,
    linesChanged,
    platforms,
    reportUrl,
    sarifUrl,
  } = input;

  const lines: string[] = [];

  // Header with fix status
  lines.push(`## CodeQual Analysis Report :robot:`);
  lines.push('');

  // Fix summary (prominent for PRO)
  if (fixes) {
    const totalActive = fixes.autoFixed + fixes.pendingReview;
    const fixRate = totalActive > 0 ? Math.round((fixes.autoFixed / totalActive) * 100) : 100;

    lines.push('### Fix Summary');
    lines.push('');
    lines.push(`| Status | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| :white_check_mark: **Auto-Fixed** | ${fixes.autoFixed} |`);
    lines.push(`| :hourglass: Pending Review | ${fixes.pendingReview} |`);
    if (fixes.alreadyResolved > 0) {
      lines.push(`| :tada: Already Resolved | ${fixes.alreadyResolved} |`);
    }
    lines.push('');
    lines.push(`**Fix Rate:** ${fixRate}%`);
    lines.push('');
  }

  // Score with before/after if applicable
  const scoreEmoji = getScoreEmoji(score.overall);
  lines.push(`**Score:** ${scoreEmoji} ${score.overall}/100 (Grade: **${score.grade}**)`);
  lines.push('');

  // Decision
  if (blocking.isBlocking) {
    lines.push(`:x: **${blocking.blockingCount} blocking issues** require attention`);
  } else if (totalIssues === 0 || (fixes && fixes.autoFixed === totalIssues)) {
    lines.push(':white_check_mark: **Ready to merge** - All issues resolved');
  } else {
    lines.push(':yellow_circle: **Review recommended** - Non-blocking issues found');
  }
  lines.push('');

  // Change summary (compact for PRO)
  lines.push(`**Changes:** ${filesChanged} files | +${linesChanged.added}/-${linesChanged.removed} lines`);
  if (platforms && platforms.length > 1) {
    lines.push(`**Platforms:** ${platforms.join(', ')}`);
  }
  lines.push('');

  // Issue breakdown (if any remaining)
  if (fixes && fixes.pendingReview > 0) {
    lines.push('### Pending Review');
    lines.push('');
    lines.push('These issues require manual attention:');
    lines.push('');

    // Show severity breakdown of pending
    const pendingBySeverity = [];
    if (severityCounts.critical > 0) pendingBySeverity.push(`:red_circle: ${severityCounts.critical} Critical`);
    if (severityCounts.high > 0) pendingBySeverity.push(`:orange_circle: ${severityCounts.high} High`);

    if (pendingBySeverity.length > 0) {
      lines.push(pendingBySeverity.join(' | '));
      lines.push('');
    }
  }

  // Apply fixes section
  if (fixes && fixes.autoFixed > 0) {
    lines.push('### Apply Fixes');
    lines.push('');
    lines.push('```bash');
    lines.push(`# Apply all verified fixes`);
    lines.push(`codequal apply --pr ${prNumber}`);
    lines.push('');
    lines.push(`# Review changes before committing`);
    lines.push(`git diff`);
    lines.push('```');
    lines.push('');
  }

  // Business impact
  if (fixes && fixes.autoFixed > 0) {
    const timeSaved = fixes.autoFixed * 10; // ~10 min per fix
    lines.push(`**Time Saved:** ~${Math.round(timeSaved / 60)}h ${timeSaved % 60}m`);
    lines.push('');
  }

  // Links
  if (reportUrl || sarifUrl) {
    lines.push('**Resources:**');
    const links = [];
    if (reportUrl) links.push(`[:page_facing_up: Full Report](${reportUrl})`);
    if (sarifUrl) links.push(`[:file_folder: SARIF](${sarifUrl})`);
    lines.push(links.join(' | '));
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('<sub>Generated by [CodeQual](https://codequal.dev) | PRO Tier | AI-Powered Fixes</sub>');

  return lines.join('\n');
}

/**
 * Generate PR summary based on tier
 */
export function generatePRSummary(input: PRSummaryInput): string {
  if (input.tier === 'basic') {
    return generateBasicPRSummary(input);
  } else {
    return generateProPRSummary(input);
  }
}

// Helper functions

function getCategoryIcon(category: string): string {
  const icons: Record<string, string> = {
    security: ':lock:',
    performance: ':zap:',
    architecture: ':building_construction:',
    dependencies: ':package:',
    codeQuality: ':sparkles:',
    codequality: ':sparkles:',
  };
  return icons[category.toLowerCase()] || ':clipboard:';
}

function formatCategory(category: string): string {
  const names: Record<string, string> = {
    security: 'Security',
    performance: 'Performance',
    architecture: 'Architecture',
    dependencies: 'Dependencies',
    codeQuality: 'Code Quality',
    codequality: 'Code Quality',
  };
  return names[category.toLowerCase()] || category;
}

function getScoreEmoji(score: number): string {
  if (score >= 90) return ':star:';
  if (score >= 70) return ':yellow_circle:';
  if (score >= 50) return ':orange_circle:';
  return ':red_circle:';
}

/**
 * Example usage and output
 */
export const EXAMPLE_BASIC_SUMMARY = `
## CodeQual Analysis Report

:warning: 12 issues found (non-blocking)

**Score:** 78/100 (Grade: **C**)

### Change Summary

| Metric | Value |
|--------|-------|
| Files Changed | 19 |
| Lines | +245 / -32 |
| Platforms | Web, Mobile, CTV, HTML5 |

### Issues Found

| Severity | Count |
|----------|-------|
| :orange_circle: High | 3 |
| :yellow_circle: Medium | 7 |
| :green_circle: Low | 2 |

**By Category:**
- :lock: Security: 2
- :sparkles: Code Quality: 8
- :package: Dependencies: 2

### Quick Actions

**IDE Integration:**
- Download SARIF file for VS Code/JetBrains one-click fixes
- Use CodeQual LSP for inline suggestions

**Resources:**
- [:page_facing_up: Full Report](https://codequal.dev/reports/123)
- [:file_folder: SARIF Export](https://storage.codequal.dev/sarif/123.json)

---

:star: **Upgrade to PRO** for AI-powered auto-fixes with before/after comparisons

<sub>Generated by [CodeQual](https://codequal.dev) | BASIC Tier</sub>
`;

export const EXAMPLE_PRO_SUMMARY = `
## CodeQual Analysis Report :robot:

### Fix Summary

| Status | Count |
|--------|-------|
| :white_check_mark: **Auto-Fixed** | 10 |
| :hourglass: Pending Review | 2 |

**Fix Rate:** 83%

**Score:** :yellow_circle: 78/100 (Grade: **C**)

:yellow_circle: **Review recommended** - Non-blocking issues found

**Changes:** 19 files | +245/-32 lines
**Platforms:** Web, Mobile, CTV, HTML5

### Pending Review

These issues require manual attention:

:orange_circle: 2 High

### Apply Fixes

\`\`\`bash
# Apply all verified fixes
codequal apply --pr 950

# Review changes before committing
git diff
\`\`\`

**Time Saved:** ~1h 40m

**Resources:**
[:page_facing_up: Full Report](https://codequal.dev/reports/123) | [:file_folder: SARIF](https://storage.codequal.dev/sarif/123.json)

---
<sub>Generated by [CodeQual](https://codequal.dev) | PRO Tier | AI-Powered Fixes</sub>
`;
