/**
 * V9 Report Formatter Module
 * 
 * Handles report generation and formatting in various formats
 */

import { 
  Issue, 
  IssueCategory, 
  AnalysisResult, 
  ReportOptions,
  IssueGroup,
  EducationalResource 
} from './v9-types';
import { V9ScoringCalculator } from './v9-scoring-calculator';
import { V9BusinessImpact } from './v9-business-impact';
import { V9EducationalResources } from './v9-educational-resources';

export class V9ReportFormatter {
  private readonly scoringCalculator: V9ScoringCalculator;
  private readonly businessImpact: V9BusinessImpact;
  private readonly educationalResources: V9EducationalResources;

  constructor() {
    this.scoringCalculator = new V9ScoringCalculator();
    this.businessImpact = new V9BusinessImpact();
    this.educationalResources = new V9EducationalResources();
  }

  /**
   * Generate report in specified format
   */
  async generateReport(
    result: AnalysisResult,
    language: string,
    options: ReportOptions = {
      format: 'markdown',
      includeCodeSnippets: true,
      includeEducationalResources: true,
      includeBusinessImpact: true,
      includeSkillScore: true,
      groupSimilarIssues: true
    }
  ): Promise<string> {
    switch (options.format) {
      case 'html':
        return this.generateHtmlReport(result, language, options);
      case 'json':
        return JSON.stringify(result, null, 2);
      case 'markdown':
      default:
        return this.generateMarkdownReport(result, language, options);
    }
  }

  /**
   * Generate markdown report
   */
  private async generateMarkdownReport(
    result: AnalysisResult,
    language: string,
    options: ReportOptions
  ): Promise<string> {
    const report: string[] = [];
    
    // Header
    report.push('# 🔍 V9 Code Quality Analysis Report\n');
    report.push(`**Language:** ${language}`);
    report.push(`**Repository:** ${result.metadata.repository}`);
    report.push(`**PR #${result.metadata.prNumber}**`);
    report.push(`**Analysis Date:** ${new Date(result.metadata.timestamp).toLocaleString()}\n`);
    
    // Executive Summary
    report.push('## 📊 Executive Summary\n');
    report.push(this.formatDecision(result));
    report.push(`**Quality Score:** ${result.qualityScore.toFixed(1)}/100 (Grade: ${result.grade})`);
    report.push(`**Confidence:** ${(result.confidence * 100).toFixed(0)}%`);
    report.push(`**Decision Reason:** ${result.reason}\n`);
    
    // Issue Summary
    report.push('## 📈 Issue Summary\n');
    this.addIssueSummary(report, result);
    
    // Business Impact
    if (options.includeBusinessImpact && result.businessImpact) {
      report.push('\n## 💼 Business Impact Analysis\n');
      this.addBusinessImpact(report, result.businessImpact);
    }
    
    // Blocking Issues
    if (result.blockingIssues.length > 0) {
      report.push('\n## 🚨 Blocking Issues (Must Fix)\n');
      report.push('These issues must be resolved before merging:\n');
      await this.addIssueSection(report, result.blockingIssues, language, options);
    }
    
    // Backlog Issues
    if (result.backlogIssues.length > 0) {
      report.push('\n## 📝 Backlog Issues (Future Sprint)\n');
      report.push('These issues should be addressed in future sprints:\n');
      await this.addIssueSection(report, result.backlogIssues, language, options);
    }
    
    // Resolved Issues
    if (result.resolvedIssues.length > 0) {
      report.push('\n## ✅ Resolved Issues\n');
      report.push('Great work! These issues were fixed in this PR:\n');
      this.addResolvedIssues(report, result.resolvedIssues);
    }
    
    // Developer Skill Score
    if (options.includeSkillScore && result.skillScore) {
      report.push('\n## 🎯 Developer Skill Analysis\n');
      this.addSkillScore(report, result.skillScore);
    }
    
    // Modified Files
    report.push('\n## 📁 Modified Files\n');
    this.addModifiedFiles(report, result.modifiedFiles);
    
    // Analysis Metadata
    report.push('\n## ⚙️ Analysis Details\n');
    this.addMetadata(report, result.metadata);
    
    // Footer
    report.push('\n---');
    report.push('*Generated by V9 Code Quality Analyzer*');
    report.push(`*Analysis completed in ${result.metadata.analysisTime}ms*`);
    
    return report.join('\n');
  }

  /**
   * Format the decision section
   */
  private formatDecision(result: AnalysisResult): string {
    const emoji = result.decision === 'approved' ? '✅' : '❌';
    const status = result.decision === 'approved' ? 'APPROVED' : 'REJECTED';
    return `**Decision:** ${emoji} **${status}**`;
  }

  /**
   * Add issue summary section
   */
  private addIssueSummary(report: string[], result: AnalysisResult): void {
    const blocking = result.blockingIssues;
    const backlog = result.backlogIssues;
    
    // Calculate points
    const blockingPoints = this.scoringCalculator.calculateFormattedPoints(blocking);
    const backlogPoints = this.scoringCalculator.calculateFormattedPoints(backlog);
    
    // Severity breakdown for blocking
    const blockingBreakdown = this.scoringCalculator.getSeverityBreakdown(blocking);
    const backlogBreakdown = this.scoringCalculator.getSeverityBreakdown(backlog);
    
    report.push('### Blocking Issues');
    this.addSeverityBreakdown(report, blockingBreakdown, '  ', false);
    report.push(`  **Total Impact:** ${blockingPoints} points\n`);
    
    report.push('### Backlog Issues');
    this.addSeverityBreakdown(report, backlogBreakdown, '  ', true);
    report.push(`  **Total Impact:** ${backlogPoints} points`);
  }

  /**
   * Add severity breakdown with proper calculation
   */
  private addSeverityBreakdown(
    report: string[],
    breakdown: Record<string, number>,
    indent: string,
    isBacklog: boolean
  ): void {
    const weights = {
      critical: 5,
      high: 3,
      medium: 1,
      low: 0.5
    };
    
    if (breakdown.critical > 0) {
      const points = breakdown.critical * weights.critical;
      report.push(`${indent}• Critical (${breakdown.critical}): ${points.toFixed(1)} ${isBacklog ? '(backlog)' : ''}`);
    }
    if (breakdown.high > 0) {
      const points = breakdown.high * weights.high;
      report.push(`${indent}• High (${breakdown.high}): ${points.toFixed(1)} ${isBacklog ? '(backlog)' : ''}`);
    }
    if (breakdown.medium > 0) {
      const points = breakdown.medium * weights.medium;
      report.push(`${indent}• Medium (${breakdown.medium}): ${points.toFixed(1)} ${isBacklog ? '(backlog)' : ''}`);
    }
    if (breakdown.low > 0) {
      const points = breakdown.low * weights.low;
      report.push(`${indent}• Low (${breakdown.low}): ${points.toFixed(1)} ${isBacklog ? '(backlog)' : ''}`);
    }
  }

  /**
   * Add business impact section
   */
  private addBusinessImpact(report: string[], impact: any): void {
    report.push(`**Summary:** ${impact.summary}\n`);
    
    report.push('### Risk Assessment');
    report.push(`- **Immediate Risk:** ${impact.immediateRisk}`);
    report.push(`- **Future Risk:** ${impact.futureRisk}\n`);
    
    report.push('### Financial Impact');
    report.push(`- **Immediate Fix Cost:** ${impact.financialImpact.fixCost}`);
    report.push(`- **Potential Exploit Cost:** ${impact.financialImpact.exploitCost}`);
    report.push(`- **ROI of Fixing:** ${impact.financialImpact.roi}\n`);
    
    report.push('### Risk by Category');
    report.push('| Category | Blocking | Backlog | Total Risk |');
    report.push('|----------|----------|---------|------------|');
    
    for (const risk of impact.riskMatrix) {
      const icon = this.businessImpact.getRiskIcon(parseFloat(risk.score));
      report.push(`| ${risk.category} | ${risk.blockingRisk.toFixed(1)} | ${risk.backlogRisk.toFixed(1)} | ${icon} ${risk.score} |`);
    }
  }

  /**
   * Add issue section with details
   */
  private async addIssueSection(
    report: string[],
    issues: Issue[],
    language: string,
    options: ReportOptions
  ): Promise<void> {
    if (options.groupSimilarIssues) {
      await this.addGroupedIssues(report, issues, language, options);
    } else {
      await this.addIndividualIssues(report, issues, language, options);
    }
  }

  /**
   * Add grouped issues
   */
  private async addGroupedIssues(
    report: string[],
    issues: Issue[],
    language: string,
    options: ReportOptions
  ): Promise<void> {
    // Group issues by pattern
    const groups = this.groupSimilarIssues(issues);
    
    for (const [pattern, groupIssues] of groups) {
      report.push(`\n### ${pattern} (${groupIssues.length} issue${groupIssues.length > 1 ? 's' : ''})\n`);
      
      // Add first issue as example
      const exampleIssue = groupIssues[0];
      await this.addIssueDetails(report, exampleIssue, language, options);
      
      // List other files if multiple
      if (groupIssues.length > 1) {
        report.push('\n**Also found in:**');
        for (let i = 1; i < Math.min(groupIssues.length, 5); i++) {
          const issue = groupIssues[i];
          report.push(`- ${issue.file}:${issue.line}`);
        }
        if (groupIssues.length > 5) {
          report.push(`- ... and ${groupIssues.length - 5} more`);
        }
      }
      
      // Add shared training resources
      if (options.includeEducationalResources) {
        const resources = await this.educationalResources.getEducationalResources(exampleIssue, language);
        if (resources.length > 0) {
          report.push('\n**📚 Training Resources:**');
          for (const resource of resources.slice(0, 3)) {
            const icon = this.educationalResources.getResourceIcon(resource.type);
            report.push(`- ${icon} [${resource.title}](${resource.url})`);
          }
        }
      }
    }
  }

  /**
   * Add individual issues
   */
  private async addIndividualIssues(
    report: string[],
    issues: Issue[],
    language: string,
    options: ReportOptions
  ): Promise<void> {
    for (const issue of issues) {
      await this.addIssueDetails(report, issue, language, options);
      report.push(''); // Add blank line between issues
    }
  }

  /**
   * Add issue details
   */
  private async addIssueDetails(
    report: string[],
    issue: Issue,
    language: string,
    options: ReportOptions
  ): Promise<void> {
    const icon = this.getCategoryIcon(issue.category);
    const severityBadge = this.getSeverityBadge(issue.severity);
    
    report.push(`#### ${icon} ${issue.title}`);
    report.push(`**File:** \`${issue.file}:${issue.line}\``);
    report.push(`**Severity:** ${severityBadge} | **Tool:** ${issue.tool} | **Agent:** ${issue.agent}`);
    report.push(`**Description:** ${issue.description}`);
    
    if (issue.impact) {
      report.push(`**Impact:** ${issue.impact}`);
    }
    
    if (options.includeCodeSnippets && issue.codeSnippet) {
      report.push('\n**Code:**');
      report.push('```' + this.getLanguageHighlight(language));
      report.push(issue.codeSnippet);
      report.push('```');
      
      if (issue.suggestedFix) {
        report.push('\n**Suggested Fix:**');
        report.push(issue.suggestedFix);
        
        if (issue.suggestedCodeSnippet) {
          report.push('```' + this.getLanguageHighlight(language));
          report.push(issue.suggestedCodeSnippet);
          report.push('```');
        }
      }
    }
  }

  /**
   * Add resolved issues section
   */
  private addResolvedIssues(report: string[], issues: Issue[]): void {
    const breakdown = this.scoringCalculator.getSeverityBreakdown(issues);
    
    report.push(`Total resolved: ${issues.length} issue(s)`);
    report.push('');
    
    if (breakdown.critical > 0) report.push(`- ✅ ${breakdown.critical} critical issue(s)`);
    if (breakdown.high > 0) report.push(`- ✅ ${breakdown.high} high issue(s)`);
    if (breakdown.medium > 0) report.push(`- ✅ ${breakdown.medium} medium issue(s)`);
    if (breakdown.low > 0) report.push(`- ✅ ${breakdown.low} low issue(s)`);
  }

  /**
   * Add skill score section
   */
  private addSkillScore(report: string[], skillScore: any): void {
    const level = this.scoringCalculator.getSkillLevel(skillScore.score);
    
    report.push(`**Developer:** ${skillScore.developer}`);
    report.push(`**Skill Level:** ${level} (${skillScore.score.toFixed(0)}/100)`);
    
    report.push('\n**Category Scores:**');
    report.push(`- Security: ${skillScore.categories.security.toFixed(0)}/100`);
    report.push(`- Performance: ${skillScore.categories.performance.toFixed(0)}/100`);
    report.push(`- Architecture: ${skillScore.categories.architecture.toFixed(0)}/100`);
    report.push(`- Dependency: ${skillScore.categories.dependency.toFixed(0)}/100`);
    report.push(`- Quality: ${skillScore.categories.quality.toFixed(0)}/100`);
    
    if (skillScore.recommendations.length > 0) {
      report.push('\n**Recommendations:**');
      for (const rec of skillScore.recommendations) {
        report.push(`- ${rec}`);
      }
    }
  }

  /**
   * Add modified files section
   */
  private addModifiedFiles(report: string[], files: string[]): void {
    report.push(`Total: ${files.length} file(s)`);
    report.push('');
    
    for (const file of files.slice(0, 10)) {
      report.push(`- ${file}`);
    }
    
    if (files.length > 10) {
      report.push(`- ... and ${files.length - 10} more`);
    }
  }

  /**
   * Add metadata section
   */
  private addMetadata(report: string[], metadata: any): void {
    report.push(`- **Language:** ${metadata.language}`);
    report.push(`- **Total Files:** ${metadata.totalFiles}`);
    report.push(`- **Modified Files:** ${metadata.modifiedFiles}`);
    report.push(`- **Analysis Time:** ${metadata.analysisTime}ms`);
    report.push(`- **Tools Used:** ${metadata.tools.join(', ')}`);
  }

  /**
   * Generate HTML report
   */
  private async generateHtmlReport(
    result: AnalysisResult,
    language: string,
    options: ReportOptions
  ): Promise<string> {
    // Convert markdown to HTML (simplified version)
    const markdown = await this.generateMarkdownReport(result, language, options);
    
    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>V9 Analysis Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; }
    h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
    h2 { color: #34495e; margin-top: 30px; }
    h3 { color: #7f8c8d; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
    pre { background: #2c3e50; color: #ecf0f1; padding: 15px; border-radius: 5px; overflow-x: auto; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background: #3498db; color: white; }
    .approved { color: #27ae60; font-weight: bold; }
    .rejected { color: #e74c3c; font-weight: bold; }
    .critical { color: #c0392b; }
    .high { color: #e74c3c; }
    .medium { color: #f39c12; }
    .low { color: #95a5a6; }
  </style>
</head>
<body>
  ${this.markdownToHtml(markdown)}
</body>
</html>`;
    
    return html;
  }

  /**
   * Simple markdown to HTML converter
   */
  private markdownToHtml(markdown: string): string {
    return markdown
      .replace(/^# (.*)/gm, '<h1>$1</h1>')
      .replace(/^## (.*)/gm, '<h2>$1</h2>')
      .replace(/^### (.*)/gm, '<h3>$1</h3>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/`(.*?)`/g, '<code>$1</code>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
      .replace(/^- (.*)/gm, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^/g, '<p>')
      .replace(/$/g, '</p>');
  }

  /**
   * Group similar issues
   */
  private groupSimilarIssues(issues: Issue[]): Map<string, Issue[]> {
    const groups = new Map<string, Issue[]>();
    
    for (const issue of issues) {
      const key = `${issue.category}-${issue.severity}-${issue.title}`;
      if (!groups.has(key)) {
        groups.set(key, []);
      }
      groups.get(key)!.push(issue);
    }
    
    return groups;
  }

  /**
   * Get category icon
   */
  private getCategoryIcon(category: IssueCategory): string {
    switch (category) {
      case 'Security': return '🔒';
      case 'Performance': return '⚡';
      case 'Architecture': return '🏗️';
      case 'Dependency': return '📦';
      case 'Quality': return '✨';
      default: return '📌';
    }
  }

  /**
   * Get severity badge
   */
  private getSeverityBadge(severity: string): string {
    switch (severity) {
      case 'critical': return '🔴 Critical';
      case 'high': return '🟠 High';
      case 'medium': return '🟡 Medium';
      case 'low': return '🟢 Low';
      default: return severity;
    }
  }

  /**
   * Get language highlight for code blocks
   */
  private getLanguageHighlight(language: string): string {
    const highlights: Record<string, string> = {
      'Rust': 'rust',
      'Java': 'java',
      'Python': 'python',
      'JavaScript': 'javascript',
      'TypeScript': 'typescript',
      'Go': 'go',
      'C++': 'cpp',
      'C#': 'csharp',
      'Ruby': 'ruby',
      'PHP': 'php'
    };
    
    return highlights[language] || language.toLowerCase();
  }
}