apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: codequal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: registry.digitalocean.com/codequal/api:v1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-credentials
