#!/bin/bash

echo "=== Good Test PRs for Comprehensive Analysis ==="
echo ""
echo "Here are some recommended PRs for testing:"
echo ""

echo "1. React Repository PRs:"
echo "   - PR #28298: React 19 RC upgrade (medium size, ~10 files)"
echo "     URL: https://github.com/facebook/react/pull/28298"
echo ""
echo "   - PR #28296: Bug fix in scheduler (small, ~3 files)"
echo "     URL: https://github.com/facebook/react/pull/28296"
echo ""
echo "   - PR #28282: Performance optimization (medium, ~8 files)"
echo "     URL: https://github.com/facebook/react/pull/28282"
echo ""

echo "2. Vue.js Repository PRs:"
echo "   - PR #9953: TypeScript improvements (large, ~15 files)"
echo "     URL: https://github.com/vuejs/core/pull/9953"
echo ""
echo "   - PR #9952: Bug fix in reactivity (small, ~4 files)"
echo "     URL: https://github.com/vuejs/core/pull/9952"
echo ""

echo "3. Express.js Repository PRs:"
echo "   - PR #5561: Security update (medium, ~6 files)"
echo "     URL: https://github.com/expressjs/express/pull/5561"
echo ""
echo "   - PR #5560: Documentation + code (small, ~3 files)"
echo "     URL: https://github.com/expressjs/express/pull/5560"
echo ""

echo "4. Node.js Repository PRs:"
echo "   - PR #51398: Performance improvement (medium, ~7 files)"
echo "     URL: https://github.com/nodejs/node/pull/51398"
echo ""

echo "To use any of these, run:"
echo "./run-comprehensive-test.sh <your-auth-token>"
echo ""
echo "Then modify the repository URL and PR number in the script, or use:"
echo "curl -X POST http://localhost:3001/api/analyze-pr \\"
echo "  -H \"Authorization: Bearer <token>\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"repositoryUrl\": \"<repo-url>\","
echo "    \"prNumber\": <pr-number>,"
echo "    \"analysisMode\": \"comprehensive\""
echo "  }'"