name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Make scripts executable
        run: chmod +x scripts/build-packages.sh
      
      - name: Build packages in order
        run: bash scripts/build-packages.sh
      
      - name: Lint
        run: npm run lint || echo "Linting failed but continuing"
      
      - name: Test
        run: npm test || echo "Tests failed but continuing"

  dependency-scan:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Set up environment variables
        run: |
          echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" >> $GITHUB_ENV
          echo "DEPENDENCY_SCAN_SEVERITY=high" >> $GITHUB_ENV
      
      - name: Run dependency scan
        if: env.SNYK_TOKEN != ''
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        with:
          args: --severity-threshold=${{ env.DEPENDENCY_SCAN_SEVERITY }}
