FROM node:18-slim

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY tsconfig.json ./
COPY lerna.json ./

# Copy packages directory
COPY packages ./packages

# Install dependencies
RUN npm install
RUN npm run build

# Set environment variables
ENV NODE_ENV production
ENV PORT 8001

# Expose the port
EXPOSE 8001

# Start the application
CMD ["npm", "start"]
